'use strict';

const Alpha3Mapping = {
	ABW: {
		isoAlpha2: 'AW',
		countryName: 'Aruba',
		unicodeFlag: '🇦🇼',
		dialCodeWithoutPlus: 297,
		dialCodeWithPlus: '+297',
		currencyCode: 'ANG',
		currencyName: 'Netherlands Antilles Guilder',
		continentCode: 'NA',
		continentName: 'North America'
	},
	AFG: {
		isoAlpha2: 'AF',
		countryName: 'Afghanistan',
		unicodeFlag: '🇦🇫',
		dialCodeWithoutPlus: 93,
		dialCodeWithPlus: '+93',
		currencyCode: 'AFN',
		currencyName: 'Afghani',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	AGO: {
		isoAlpha2: 'AO',
		countryName: 'Angola',
		unicodeFlag: '🇦🇴',
		dialCodeWithoutPlus: 244,
		dialCodeWithPlus: '+244',
		currencyCode: 'AOA',
		currencyName: 'Angolan kwanza',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	AIA: {
		isoAlpha2: 'AI',
		countryName: 'Anguilla',
		unicodeFlag: '🇦🇮',
		dialCodeWithoutPlus: 1264,
		dialCodeWithPlus: '+1264',
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	ALA: {
		isoAlpha2: 'AX',
		countryName: 'Aland Islands',
		unicodeFlag: '🇦🇽',
		dialCodeWithoutPlus: 358,
		dialCodeWithPlus: '+358',
		currencyCode: 'EUR',
		currencyName: 'Euro',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	ALB: {
		isoAlpha2: 'AL',
		countryName: 'Albania',
		unicodeFlag: '🇦🇱',
		dialCodeWithoutPlus: 355,
		dialCodeWithPlus: '+355',
		currencyCode: 'ALL',
		currencyName: 'Lek',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	AND: {
		isoAlpha2: 'AD',
		countryName: 'Andorra',
		unicodeFlag: '🇦🇩',
		dialCodeWithoutPlus: 376,
		dialCodeWithPlus: '+376',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	ARE: {
		isoAlpha2: 'AE',
		countryName: 'United Arab Emirates',
		unicodeFlag: '🇦🇪',
		dialCodeWithoutPlus: 971,
		dialCodeWithPlus: '+971',
		currencyCode: 'AED',
		currencyName: 'Dirham',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	ARG: {
		isoAlpha2: 'AR',
		countryName: 'Argentina',
		unicodeFlag: '🇦🇷',
		dialCodeWithoutPlus: 54,
		dialCodeWithPlus: '+54',
		currencyCode: 'ARS',
		currencyName: 'Peso',
		continentCode: 'SA',
		continentName: 'South America'
	},
	ARM: {
		isoAlpha2: 'AM',
		countryName: 'Armenia',
		unicodeFlag: '🇦🇲',
		dialCodeWithoutPlus: 374,
		dialCodeWithPlus: '+374',
		currencyCode: 'AMD',
		currencyName: 'Dram',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	ASM: {
		isoAlpha2: 'AS',
		countryName: 'American Samoa',
		unicodeFlag: '🇦🇸',
		dialCodeWithoutPlus: 1684,
		dialCodeWithPlus: '+1684',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	ATA: {
		isoAlpha2: 'AQ',
		countryName: 'Antarctica',
		unicodeFlag: '🇦🇶',
		dialCodeWithoutPlus: 672,
		dialCodeWithPlus: '+672',
		currencyCode: 'AQD',
		currencyName: 'Antarctican dollar',
		continentCode: 'AN',
		continentName: 'Antarctica'
	},
	ATF: {
		isoAlpha2: 'TF',
		countryName: 'French Southern Territories',
		unicodeFlag: '🇹🇫',
		dialCodeWithoutPlus: 262,
		dialCodeWithPlus: '+262',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'AN',
		continentName: 'Antarctica'
	},
	ATG: {
		isoAlpha2: 'AG',
		countryName: 'Antigua and Barbuda',
		unicodeFlag: '🇦🇬',
		dialCodeWithoutPlus: 1268,
		dialCodeWithPlus: '+1268',
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	AUS: {
		isoAlpha2: 'AU',
		countryName: 'Australia',
		unicodeFlag: '🇦🇺',
		dialCodeWithoutPlus: 61,
		dialCodeWithPlus: '+61',
		currencyCode: 'AUD',
		currencyName: 'Australian Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	AUT: {
		isoAlpha2: 'AT',
		countryName: 'Austria',
		unicodeFlag: '🇦🇹',
		dialCodeWithoutPlus: 43,
		dialCodeWithPlus: '+43',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	AZE: {
		isoAlpha2: 'AZ',
		countryName: 'Azerbaijan',
		unicodeFlag: '🇦🇿',
		dialCodeWithoutPlus: 994,
		dialCodeWithPlus: '+994',
		currencyCode: 'AZN',
		currencyName: 'Manat',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	BDI: {
		isoAlpha2: 'BI',
		countryName: 'Burundi',
		unicodeFlag: '🇧🇮',
		dialCodeWithoutPlus: 257,
		dialCodeWithPlus: '+257',
		currencyCode: 'BIF',
		currencyName: 'Burundi Franc',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	BEL: {
		isoAlpha2: 'BE',
		countryName: 'Belgium',
		unicodeFlag: '🇧🇪',
		dialCodeWithoutPlus: 32,
		dialCodeWithPlus: '+32',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	BEN: {
		isoAlpha2: 'BJ',
		countryName: 'Benin',
		unicodeFlag: '🇧🇯',
		dialCodeWithoutPlus: 229,
		dialCodeWithPlus: '+229',
		currencyCode: 'XOF',
		currencyName: 'CFA Franc BCEAO',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	BES: {
		isoAlpha2: 'BQ',
		countryName: 'Bonaire, Sint Eustatius and Saba',
		unicodeFlag: '🇧🇶',
		dialCodeWithoutPlus: 599,
		dialCodeWithPlus: '+599',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'NA',
		continentName: 'North America'
	},
	BFA: {
		isoAlpha2: 'BF',
		countryName: 'Burkina Faso',
		unicodeFlag: '🇧🇫',
		dialCodeWithoutPlus: 226,
		dialCodeWithPlus: '+226',
		currencyCode: 'XOF',
		currencyName: 'CFA Franc BCEAO',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	BGD: {
		isoAlpha2: 'BD',
		countryName: 'Bangladesh',
		unicodeFlag: '🇧🇩',
		dialCodeWithoutPlus: 880,
		dialCodeWithPlus: '+880',
		currencyCode: 'BDT',
		currencyName: 'Taka',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	BGR: {
		isoAlpha2: 'BG',
		countryName: 'Bulgaria',
		unicodeFlag: '🇧🇬',
		dialCodeWithoutPlus: 359,
		dialCodeWithPlus: '+359',
		currencyCode: 'BGN',
		currencyName: 'Lev',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	BHR: {
		isoAlpha2: 'BH',
		countryName: 'Bahrain',
		unicodeFlag: '🇧🇭',
		dialCodeWithoutPlus: 973,
		dialCodeWithPlus: '+973',
		currencyCode: 'BHD',
		currencyName: 'Bahraini Dinar',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	BHS: {
		isoAlpha2: 'BS',
		countryName: 'Bahamas',
		unicodeFlag: '🇧🇸',
		dialCodeWithoutPlus: 1242,
		dialCodeWithPlus: '+1242',
		currencyCode: 'BSD',
		currencyName: 'Bahamian Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	BIH: {
		isoAlpha2: 'BA',
		countryName: 'Bosnia and Herzegovina',
		unicodeFlag: '🇧🇦',
		dialCodeWithoutPlus: 387,
		dialCodeWithPlus: '+387',
		currencyCode: 'BAM',
		currencyName: 'Bosnia and Herzegovina convertible mark',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	BLM: {
		isoAlpha2: 'BL',
		countryName: 'Saint Barthélemy',
		unicodeFlag: '🇧🇱',
		dialCodeWithoutPlus: 590,
		dialCodeWithPlus: '+590',
		currencyCode: 'EUR',
		currencyName: 'Euro',
		continentCode: 'NA',
		continentName: 'North America'
	},
	BLR: {
		isoAlpha2: 'BY',
		countryName: 'Belarus',
		unicodeFlag: '🇧🇾',
		dialCodeWithoutPlus: 375,
		dialCodeWithPlus: '+375',
		currencyCode: 'BYR',
		currencyName: 'Belarus Ruble',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	BLZ: {
		isoAlpha2: 'BZ',
		countryName: 'Belize',
		unicodeFlag: '🇧🇿',
		dialCodeWithoutPlus: 501,
		dialCodeWithPlus: '+501',
		currencyCode: 'BZD',
		currencyName: 'Belizean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	BMU: {
		isoAlpha2: 'BM',
		countryName: 'Bermuda',
		unicodeFlag: '🇧🇲',
		dialCodeWithoutPlus: 1441,
		dialCodeWithPlus: '+1441',
		currencyCode: 'BMD',
		currencyName: 'Bermudian Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	BOL: {
		isoAlpha2: 'BO',
		countryName: 'Bolivia (Plurinational State of)',
		unicodeFlag: '🇧🇴',
		dialCodeWithoutPlus: 591,
		dialCodeWithPlus: '+591',
		currencyCode: 'BOB',
		currencyName: 'Boliviano',
		continentCode: 'SA',
		continentName: 'South America'
	},
	BRA: {
		isoAlpha2: 'BR',
		countryName: 'Brazil',
		unicodeFlag: '🇧🇷',
		dialCodeWithoutPlus: 55,
		dialCodeWithPlus: '+55',
		currencyCode: 'BRL',
		currencyName: 'Brazil',
		continentCode: 'SA',
		continentName: 'South America'
	},
	BRB: {
		isoAlpha2: 'BB',
		countryName: 'Barbados',
		unicodeFlag: '🇧🇧',
		dialCodeWithoutPlus: 1246,
		dialCodeWithPlus: '+1246',
		currencyCode: 'BBD',
		currencyName: 'Barbadian Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	BRN: {
		isoAlpha2: 'BN',
		countryName: 'Brunei Darussalam',
		unicodeFlag: '🇧🇳',
		dialCodeWithoutPlus: 673,
		dialCodeWithPlus: '+673',
		currencyCode: 'BND',
		currencyName: 'Bruneian Dollar',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	BTN: {
		isoAlpha2: 'BT',
		countryName: 'Bhutan',
		unicodeFlag: '🇧🇹',
		dialCodeWithoutPlus: 975,
		dialCodeWithPlus: '+975',
		currencyCode: 'INR',
		currencyName: 'Indian Rupee',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	BVT: {
		isoAlpha2: 'BV',
		countryName: 'Bouvet Island',
		unicodeFlag: '🇧🇻',
		dialCodeWithoutPlus: 47,
		dialCodeWithPlus: '+47',
		currencyCode: 'NOK',
		currencyName: 'Norwegian Krone',
		continentCode: 'AN',
		continentName: 'Antarctica'
	},
	BWA: {
		isoAlpha2: 'BW',
		countryName: 'Botswana',
		unicodeFlag: '🇧🇼',
		dialCodeWithoutPlus: 267,
		dialCodeWithPlus: '+267',
		currencyCode: 'BWP',
		currencyName: 'Pula',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	CAF: {
		isoAlpha2: 'CF',
		countryName: 'Central African Republic',
		unicodeFlag: '🇨🇫',
		dialCodeWithoutPlus: 236,
		dialCodeWithPlus: '+236',
		currencyCode: 'XAF',
		currencyName: 'CFA Franc BEAC',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	CAN: {
		isoAlpha2: 'CA',
		countryName: 'Canada',
		unicodeFlag: '🇨🇦',
		dialCodeWithoutPlus: 1,
		dialCodeWithPlus: '+1',
		currencyCode: 'CAD',
		currencyName: 'Canadian Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	CCK: {
		isoAlpha2: 'CC',
		countryName: 'Cocos (Keeling) Islands',
		unicodeFlag: '🇨🇨',
		dialCodeWithoutPlus: 61,
		dialCodeWithPlus: '+61',
		currencyCode: 'AUD',
		currencyName: 'Australian Dollars',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	CHE: {
		isoAlpha2: 'CH',
		countryName: 'Switzerland',
		unicodeFlag: '🇨🇭',
		dialCodeWithoutPlus: 41,
		dialCodeWithPlus: '+41',
		currencyCode: 'CHF',
		currencyName: 'Swiss Franc',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	CHL: {
		isoAlpha2: 'CL',
		countryName: 'Chile',
		unicodeFlag: '🇨🇱',
		dialCodeWithoutPlus: 56,
		dialCodeWithPlus: '+56',
		currencyCode: 'CLP',
		currencyName: 'Chilean Peso',
		continentCode: 'SA',
		continentName: 'South America'
	},
	CHN: {
		isoAlpha2: 'CN',
		countryName: 'China',
		unicodeFlag: '🇨🇳',
		dialCodeWithoutPlus: 86,
		dialCodeWithPlus: '+86',
		currencyCode: 'CNY',
		currencyName: 'Yuan Renminbi',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	CIV: {
		isoAlpha2: 'CI',
		countryName: 'Côte d\'Ivoire',
		unicodeFlag: '🇨🇮',
		dialCodeWithoutPlus: 225,
		dialCodeWithPlus: '+225',
		currencyCode: 'XOF',
		currencyName: 'CFA Franc BCEAO',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	CMR: {
		isoAlpha2: 'CM',
		countryName: 'Cameroon',
		unicodeFlag: '🇨🇲',
		dialCodeWithoutPlus: 237,
		dialCodeWithPlus: '+237',
		currencyCode: 'XAF',
		currencyName: 'CFA Franc BEAC',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	COD: {
		isoAlpha2: 'CD',
		countryName: 'Democratic Republic of the Congo',
		unicodeFlag: '🇨🇩',
		dialCodeWithoutPlus: 243,
		dialCodeWithPlus: '+243',
		currencyCode: 'CDF',
		currencyName: 'Congolese Frank',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	COG: {
		isoAlpha2: 'CG',
		countryName: 'Republic of the Congo',
		unicodeFlag: '🇨🇬',
		dialCodeWithoutPlus: 242,
		dialCodeWithPlus: '+242',
		currencyCode: 'XAF',
		currencyName: 'CFA Franc BEAC',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	COK: {
		isoAlpha2: 'CK',
		countryName: 'Cook Islands',
		unicodeFlag: '🇨🇰',
		dialCodeWithoutPlus: 682,
		dialCodeWithPlus: '+682',
		currencyCode: 'NZD',
		currencyName: 'New Zealand Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	COL: {
		isoAlpha2: 'CO',
		countryName: 'Colombia',
		unicodeFlag: '🇨🇴',
		dialCodeWithoutPlus: 57,
		dialCodeWithPlus: '+57',
		currencyCode: 'COP',
		currencyName: 'Peso',
		continentCode: 'SA',
		continentName: 'South America'
	},
	COM: {
		isoAlpha2: 'KM',
		countryName: 'Comoros',
		unicodeFlag: '🇰🇲',
		dialCodeWithoutPlus: 269,
		dialCodeWithPlus: '+269',
		currencyCode: 'KMF',
		currencyName: 'Comoran Franc',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	CPV: {
		isoAlpha2: 'CV',
		countryName: 'Cabo Verde',
		unicodeFlag: '🇨🇻',
		dialCodeWithoutPlus: 238,
		dialCodeWithPlus: '+238',
		currencyCode: 'CVE',
		currencyName: 'Escudo',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	CRI: {
		isoAlpha2: 'CR',
		countryName: 'Costa Rica',
		unicodeFlag: '🇨🇷',
		dialCodeWithoutPlus: 506,
		dialCodeWithPlus: '+506',
		currencyCode: 'CRC',
		currencyName: 'Costa Rican Colon',
		continentCode: 'NA',
		continentName: 'North America'
	},
	CUB: {
		isoAlpha2: 'CU',
		countryName: 'Cuba',
		unicodeFlag: '🇨🇺',
		dialCodeWithoutPlus: 53,
		dialCodeWithPlus: '+53',
		currencyCode: 'CUP',
		currencyName: 'Cuban Peso',
		continentCode: 'NA',
		continentName: 'North America'
	},
	CUW: {
		isoAlpha2: 'CW',
		countryName: 'Curaçao',
		unicodeFlag: '🇨🇼',
		dialCodeWithoutPlus: 599,
		dialCodeWithPlus: '+599',
		currencyCode: 'ANG',
		currencyName: 'Netherlands Antillean guilder',
		continentCode: 'NA',
		continentName: 'North America'
	},
	CXR: {
		isoAlpha2: 'CX',
		countryName: 'Christmas Island',
		unicodeFlag: '🇨🇽',
		dialCodeWithoutPlus: 61,
		dialCodeWithPlus: '+61',
		currencyCode: 'AUD',
		currencyName: 'Australian Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	CYM: {
		isoAlpha2: 'KY',
		countryName: 'Cayman Islands',
		unicodeFlag: '🇰🇾',
		dialCodeWithoutPlus: 1345,
		dialCodeWithPlus: '+1345',
		currencyCode: 'KYD',
		currencyName: 'Caymanian Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	CYP: {
		isoAlpha2: 'CY',
		countryName: 'Cyprus',
		unicodeFlag: '🇨🇾',
		dialCodeWithoutPlus: 357,
		dialCodeWithPlus: '+357',
		currencyCode: 'CYP',
		currencyName: 'Cypriot Pound',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	CZE: {
		isoAlpha2: 'CZ',
		countryName: 'Czechia',
		unicodeFlag: '🇨🇿',
		dialCodeWithoutPlus: 420,
		dialCodeWithPlus: '+420',
		currencyCode: 'CZK',
		currencyName: 'Koruna',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	DEU: {
		isoAlpha2: 'DE',
		countryName: 'Germany',
		unicodeFlag: '🇩🇪',
		dialCodeWithoutPlus: 49,
		dialCodeWithPlus: '+49',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	DJI: {
		isoAlpha2: 'DJ',
		countryName: 'Djibouti',
		unicodeFlag: '🇩🇯',
		dialCodeWithoutPlus: 253,
		dialCodeWithPlus: '+253',
		currencyCode: 'DJF',
		currencyName: 'Djiboutian Franc',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	DMA: {
		isoAlpha2: 'DM',
		countryName: 'Dominica',
		unicodeFlag: '🇩🇲',
		dialCodeWithoutPlus: 1767,
		dialCodeWithPlus: '+1767',
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	DNK: {
		isoAlpha2: 'DK',
		countryName: 'Denmark',
		unicodeFlag: '🇩🇰',
		dialCodeWithoutPlus: 45,
		dialCodeWithPlus: '+45',
		currencyCode: 'DKK',
		currencyName: 'Danish Krone',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	DOM: {
		isoAlpha2: 'DO',
		countryName: 'Dominican Republic',
		unicodeFlag: '🇩🇴',
		dialCodeWithoutPlus: 1,
		dialCodeWithPlus: '+1',
		currencyCode: 'DOP',
		currencyName: 'Dominican Peso',
		continentCode: 'NA',
		continentName: 'North America'
	},
	DZA: {
		isoAlpha2: 'DZ',
		countryName: 'Algeria',
		unicodeFlag: '🇩🇿',
		dialCodeWithoutPlus: 213,
		dialCodeWithPlus: '+213',
		currencyCode: 'DZD',
		currencyName: 'Algerian Dinar',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	ECU: {
		isoAlpha2: 'EC',
		countryName: 'Ecuador',
		unicodeFlag: '🇪🇨',
		dialCodeWithoutPlus: 593,
		dialCodeWithPlus: '+593',
		currencyCode: 'ECS',
		currencyName: 'Sucre',
		continentCode: 'SA',
		continentName: 'South America'
	},
	EGY: {
		isoAlpha2: 'EG',
		countryName: 'Egypt',
		unicodeFlag: '🇪🇬',
		dialCodeWithoutPlus: 20,
		dialCodeWithPlus: '+20',
		currencyCode: 'EGP',
		currencyName: 'Egyptian Pound',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	ERI: {
		isoAlpha2: 'ER',
		countryName: 'Eritrea',
		unicodeFlag: '🇪🇷',
		dialCodeWithoutPlus: 291,
		dialCodeWithPlus: '+291',
		currencyCode: 'ETB',
		currencyName: 'Ethiopian Birr',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	ESH: {
		isoAlpha2: 'EH',
		countryName: 'Western Sahara',
		unicodeFlag: '🇪🇭',
		dialCodeWithoutPlus: 212,
		dialCodeWithPlus: '+212',
		currencyCode: 'MAD',
		currencyName: 'Dirham',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	ESP: {
		isoAlpha2: 'ES',
		countryName: 'Spain',
		unicodeFlag: '🇪🇸',
		dialCodeWithoutPlus: 34,
		dialCodeWithPlus: '+34',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	EST: {
		isoAlpha2: 'EE',
		countryName: 'Estonia',
		unicodeFlag: '🇪🇪',
		dialCodeWithoutPlus: 372,
		dialCodeWithPlus: '+372',
		currencyCode: 'EEK',
		currencyName: 'Estonian Kroon',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	ETH: {
		isoAlpha2: 'ET',
		countryName: 'Ethiopia',
		unicodeFlag: '🇪🇹',
		dialCodeWithoutPlus: 251,
		dialCodeWithPlus: '+251',
		currencyCode: 'ETB',
		currencyName: 'Ethiopian Birr',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	FIN: {
		isoAlpha2: 'FI',
		countryName: 'Finland',
		unicodeFlag: '🇫🇮',
		dialCodeWithoutPlus: 358,
		dialCodeWithPlus: '+358',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	FJI: {
		isoAlpha2: 'FJ',
		countryName: 'Fiji',
		unicodeFlag: '🇫🇯',
		dialCodeWithoutPlus: 679,
		dialCodeWithPlus: '+679',
		currencyCode: 'FJD',
		currencyName: 'Fijian Dollar',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	FLK: {
		isoAlpha2: 'FK',
		countryName: 'Falkland Islands (Malvinas)',
		unicodeFlag: '🇫🇰',
		dialCodeWithoutPlus: 500,
		dialCodeWithPlus: '+500',
		currencyCode: 'FKP',
		currencyName: 'Falkland Pound',
		continentCode: 'SA',
		continentName: 'South America'
	},
	FRA: {
		isoAlpha2: 'FR',
		countryName: 'France',
		unicodeFlag: '🇫🇷',
		dialCodeWithoutPlus: 33,
		dialCodeWithPlus: '+33',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	FRO: {
		isoAlpha2: 'FO',
		countryName: 'Faroe Islands',
		unicodeFlag: '🇫🇴',
		dialCodeWithoutPlus: 298,
		dialCodeWithPlus: '+298',
		currencyCode: 'DKK',
		currencyName: 'Danish Krone',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	FSM: {
		isoAlpha2: 'FM',
		countryName: 'Micronesia (Federated States of)',
		unicodeFlag: '🇫🇲',
		dialCodeWithoutPlus: 691,
		dialCodeWithPlus: '+691',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	GAB: {
		isoAlpha2: 'GA',
		countryName: 'Gabon',
		unicodeFlag: '🇬🇦',
		dialCodeWithoutPlus: 241,
		dialCodeWithPlus: '+241',
		currencyCode: 'XAF',
		currencyName: 'CFA Franc BEAC',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	GBR: {
		isoAlpha2: 'GB',
		countryName: 'United Kingdom of Great Britain and Northern Ireland',
		unicodeFlag: '🇬🇧',
		dialCodeWithoutPlus: 44,
		dialCodeWithPlus: '+44',
		currencyCode: 'GBP',
		currencyName: 'Sterling',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	GEO: {
		isoAlpha2: 'GE',
		countryName: 'Georgia',
		unicodeFlag: '🇬🇪',
		dialCodeWithoutPlus: 995,
		dialCodeWithPlus: '+995',
		currencyCode: 'GEL',
		currencyName: 'Lari',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	GGY: {
		isoAlpha2: 'GG',
		countryName: 'Guernsey',
		unicodeFlag: '🇬🇬',
		dialCodeWithoutPlus: 44,
		dialCodeWithPlus: '+44',
		currencyCode: 'GGP',
		currencyName: 'Guernsey pound',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	GHA: {
		isoAlpha2: 'GH',
		countryName: 'Ghana',
		unicodeFlag: '🇬🇭',
		dialCodeWithoutPlus: 233,
		dialCodeWithPlus: '+233',
		currencyCode: 'GHS',
		currencyName: 'Ghana cedi',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	GIB: {
		isoAlpha2: 'GI',
		countryName: 'Gibraltar',
		unicodeFlag: '🇬🇮',
		dialCodeWithoutPlus: 350,
		dialCodeWithPlus: '+350',
		currencyCode: 'GIP',
		currencyName: 'Gibraltar Pound',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	GIN: {
		isoAlpha2: 'GN',
		countryName: 'Guinea',
		unicodeFlag: '🇬🇳',
		dialCodeWithoutPlus: 224,
		dialCodeWithPlus: '+224',
		currencyCode: 'GNF',
		currencyName: 'Guinean Franc',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	GLP: {
		isoAlpha2: 'GP',
		countryName: 'Guadeloupe',
		unicodeFlag: '🇬🇵',
		dialCodeWithoutPlus: 590,
		dialCodeWithPlus: '+590',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'NA',
		continentName: 'North America'
	},
	GMB: {
		isoAlpha2: 'GM',
		countryName: 'Gambia',
		unicodeFlag: '🇬🇲',
		dialCodeWithoutPlus: 220,
		dialCodeWithPlus: '+220',
		currencyCode: 'GMD',
		currencyName: 'Dalasi',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	GNB: {
		isoAlpha2: 'GW',
		countryName: 'Guinea-Bissau',
		unicodeFlag: '🇬🇼',
		dialCodeWithoutPlus: 245,
		dialCodeWithPlus: '+245',
		currencyCode: 'XOF',
		currencyName: 'CFA Franc BCEAO',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	GNQ: {
		isoAlpha2: 'GQ',
		countryName: 'Equatorial Guinea',
		unicodeFlag: '🇬🇶',
		dialCodeWithoutPlus: 240,
		dialCodeWithPlus: '+240',
		currencyCode: 'XAF',
		currencyName: 'CFA Franc BEAC',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	GRC: {
		isoAlpha2: 'GR',
		countryName: 'Greece',
		unicodeFlag: '🇬🇷',
		dialCodeWithoutPlus: 30,
		dialCodeWithPlus: '+30',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	GRD: {
		isoAlpha2: 'GD',
		countryName: 'Grenada',
		unicodeFlag: '🇬🇩',
		dialCodeWithoutPlus: 1473,
		dialCodeWithPlus: '+1473',
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	GRL: {
		isoAlpha2: 'GL',
		countryName: 'Greenland',
		unicodeFlag: '🇬🇱',
		dialCodeWithoutPlus: 299,
		dialCodeWithPlus: '+299',
		currencyCode: 'DKK',
		currencyName: 'Danish Krone',
		continentCode: 'NA',
		continentName: 'North America'
	},
	GTM: {
		isoAlpha2: 'GT',
		countryName: 'Guatemala',
		unicodeFlag: '🇬🇹',
		dialCodeWithoutPlus: 502,
		dialCodeWithPlus: '+502',
		currencyCode: 'GTQ',
		currencyName: 'Quetzal',
		continentCode: 'NA',
		continentName: 'North America'
	},
	GUF: {
		isoAlpha2: 'GF',
		countryName: 'French Guiana',
		unicodeFlag: '🇬🇫',
		dialCodeWithoutPlus: 594,
		dialCodeWithPlus: '+594',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'SA',
		continentName: 'South America'
	},
	GUM: {
		isoAlpha2: 'GU',
		countryName: 'Guam',
		unicodeFlag: '🇬🇺',
		dialCodeWithoutPlus: 1671,
		dialCodeWithPlus: '+1671',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	GUY: {
		isoAlpha2: 'GY',
		countryName: 'Guyana',
		unicodeFlag: '🇬🇾',
		dialCodeWithoutPlus: 592,
		dialCodeWithPlus: '+592',
		currencyCode: 'GYD',
		currencyName: 'Guyanaese Dollar',
		continentCode: 'SA',
		continentName: 'South America'
	},
	HKG: {
		isoAlpha2: 'HK',
		countryName: 'Hong Kong',
		unicodeFlag: '🇭🇰',
		dialCodeWithoutPlus: 852,
		dialCodeWithPlus: '+852',
		currencyCode: 'HKD',
		currencyName: 'HKD',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	HMD: {
		isoAlpha2: 'HM',
		countryName: 'Heard Island and McDonald Islands',
		unicodeFlag: '🇭🇲',
		dialCodeWithoutPlus: 672,
		dialCodeWithPlus: '+672',
		currencyCode: 'AUD',
		currencyName: 'Australian Dollars',
		continentCode: 'AN',
		continentName: 'Antarctica'
	},
	HND: {
		isoAlpha2: 'HN',
		countryName: 'Honduras',
		unicodeFlag: '🇭🇳',
		dialCodeWithoutPlus: 504,
		dialCodeWithPlus: '+504',
		currencyCode: 'HNL',
		currencyName: 'Lempira',
		continentCode: 'NA',
		continentName: 'North America'
	},
	HRV: {
		isoAlpha2: 'HR',
		countryName: 'Croatia',
		unicodeFlag: '🇭🇷',
		dialCodeWithoutPlus: 385,
		dialCodeWithPlus: '+385',
		currencyCode: 'HRK',
		currencyName: 'Croatian Dinar',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	HTI: {
		isoAlpha2: 'HT',
		countryName: 'Haiti',
		unicodeFlag: '🇭🇹',
		dialCodeWithoutPlus: 509,
		dialCodeWithPlus: '+509',
		currencyCode: 'HTG',
		currencyName: 'Gourde',
		continentCode: 'NA',
		continentName: 'North America'
	},
	HUN: {
		isoAlpha2: 'HU',
		countryName: 'Hungary',
		unicodeFlag: '🇭🇺',
		dialCodeWithoutPlus: 36,
		dialCodeWithPlus: '+36',
		currencyCode: 'HUF',
		currencyName: 'Forint',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	IDN: {
		isoAlpha2: 'ID',
		countryName: 'Indonesia',
		unicodeFlag: '🇮🇩',
		dialCodeWithoutPlus: 62,
		dialCodeWithPlus: '+62',
		currencyCode: 'IDR',
		currencyName: 'Indonesian Rupiah',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	IMN: {
		isoAlpha2: 'IM',
		countryName: 'Isle of Man',
		unicodeFlag: '🇮🇲',
		dialCodeWithoutPlus: 44,
		dialCodeWithPlus: '+44',
		currencyCode: 'GBP',
		currencyName: 'Manx pound',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	IND: {
		isoAlpha2: 'IN',
		countryName: 'India',
		unicodeFlag: '🇮🇳',
		dialCodeWithoutPlus: 91,
		dialCodeWithPlus: '+91',
		currencyCode: 'INR',
		currencyName: 'Indian Rupee',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	IOT: {
		isoAlpha2: 'IO',
		countryName: 'British Indian Ocean Territory',
		unicodeFlag: '🇮🇴',
		dialCodeWithoutPlus: 246,
		dialCodeWithPlus: '+246',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	IRL: {
		isoAlpha2: 'IE',
		countryName: 'Ireland',
		unicodeFlag: '🇮🇪',
		dialCodeWithoutPlus: 353,
		dialCodeWithPlus: '+353',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	IRN: {
		isoAlpha2: 'IR',
		countryName: 'Iran',
		unicodeFlag: '🇮🇷',
		dialCodeWithoutPlus: 98,
		dialCodeWithPlus: '+98',
		currencyCode: 'IRR',
		currencyName: 'Iranian Rial',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	IRQ: {
		isoAlpha2: 'IQ',
		countryName: 'Iraq',
		unicodeFlag: '🇮🇶',
		dialCodeWithoutPlus: 964,
		dialCodeWithPlus: '+964',
		currencyCode: 'IQD',
		currencyName: 'Iraqi Dinar',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	ISL: {
		isoAlpha2: 'IS',
		countryName: 'Iceland',
		unicodeFlag: '🇮🇸',
		dialCodeWithoutPlus: 354,
		dialCodeWithPlus: '+354',
		currencyCode: 'ISK',
		currencyName: 'Icelandic Krona',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	ISR: {
		isoAlpha2: 'IL',
		countryName: 'Israel',
		unicodeFlag: '🇮🇱',
		dialCodeWithoutPlus: 972,
		dialCodeWithPlus: '+972',
		currencyCode: 'ILS',
		currencyName: 'Shekel',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	ITA: {
		isoAlpha2: 'IT',
		countryName: 'Italy',
		unicodeFlag: '🇮🇹',
		dialCodeWithoutPlus: 39,
		dialCodeWithPlus: '+39',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	JAM: {
		isoAlpha2: 'JM',
		countryName: 'Jamaica',
		unicodeFlag: '🇯🇲',
		dialCodeWithoutPlus: 1876,
		dialCodeWithPlus: '+1876',
		currencyCode: 'JMD',
		currencyName: 'Jamaican Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	JEY: {
		isoAlpha2: 'JE',
		countryName: 'Jersey',
		unicodeFlag: '🇯🇪',
		dialCodeWithoutPlus: 44,
		dialCodeWithPlus: '+44',
		currencyCode: 'GBP',
		currencyName: 'Sterling',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	JOR: {
		isoAlpha2: 'JO',
		countryName: 'Jordan',
		unicodeFlag: '🇯🇴',
		dialCodeWithoutPlus: 962,
		dialCodeWithPlus: '+962',
		currencyCode: 'JOD',
		currencyName: 'Jordanian Dinar',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	JPN: {
		isoAlpha2: 'JP',
		countryName: 'Japan',
		unicodeFlag: '🇯🇵',
		dialCodeWithoutPlus: 81,
		dialCodeWithPlus: '+81',
		currencyCode: 'JPY',
		currencyName: 'Japanese Yen',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	KAZ: {
		isoAlpha2: 'KZ',
		countryName: 'Kazakhstan',
		unicodeFlag: '🇰🇿',
		dialCodeWithoutPlus: 7,
		dialCodeWithPlus: '+7',
		currencyCode: 'KZT',
		currencyName: 'Tenge',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	KEN: {
		isoAlpha2: 'KE',
		countryName: 'Kenya',
		unicodeFlag: '🇰🇪',
		dialCodeWithoutPlus: 254,
		dialCodeWithPlus: '+254',
		currencyCode: 'KES',
		currencyName: 'Kenyan Shilling',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	KGZ: {
		isoAlpha2: 'KG',
		countryName: 'Kyrgyzstan',
		unicodeFlag: '🇰🇬',
		dialCodeWithoutPlus: 996,
		dialCodeWithPlus: '+996',
		currencyCode: 'KGS',
		currencyName: 'Som',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	KHM: {
		isoAlpha2: 'KH',
		countryName: 'Cambodia',
		unicodeFlag: '🇰🇭',
		dialCodeWithoutPlus: 855,
		dialCodeWithPlus: '+855',
		currencyCode: 'KHR',
		currencyName: 'Riel',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	KIR: {
		isoAlpha2: 'KI',
		countryName: 'Kiribati',
		unicodeFlag: '🇰🇮',
		dialCodeWithoutPlus: 686,
		dialCodeWithPlus: '+686',
		currencyCode: 'AUD',
		currencyName: 'Australian Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	KNA: {
		isoAlpha2: 'KN',
		countryName: 'Saint Kitts and Nevis',
		unicodeFlag: '🇰🇳',
		dialCodeWithoutPlus: 1869,
		dialCodeWithPlus: '+1869',
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	KOR: {
		isoAlpha2: 'KR',
		countryName: 'South Korea',
		unicodeFlag: '🇰🇷',
		dialCodeWithoutPlus: 82,
		dialCodeWithPlus: '+82',
		currencyCode: 'KRW',
		currencyName: 'Won',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	KWT: {
		isoAlpha2: 'KW',
		countryName: 'Kuwait',
		unicodeFlag: '🇰🇼',
		dialCodeWithoutPlus: 965,
		dialCodeWithPlus: '+965',
		currencyCode: 'KWD',
		currencyName: 'Kuwaiti Dinar',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	LAO: {
		isoAlpha2: 'LA',
		countryName: 'Laos',
		unicodeFlag: '🇱🇦',
		dialCodeWithoutPlus: 856,
		dialCodeWithPlus: '+856',
		currencyCode: 'LAK',
		currencyName: 'Kip',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	LBN: {
		isoAlpha2: 'LB',
		countryName: 'Lebanon',
		unicodeFlag: '🇱🇧',
		dialCodeWithoutPlus: 961,
		dialCodeWithPlus: '+961',
		currencyCode: 'LBP',
		currencyName: 'Lebanese Pound',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	LBR: {
		isoAlpha2: 'LR',
		countryName: 'Liberia',
		unicodeFlag: '🇱🇷',
		dialCodeWithoutPlus: 231,
		dialCodeWithPlus: '+231',
		currencyCode: 'LRD',
		currencyName: 'Liberian Dollar',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	LBY: {
		isoAlpha2: 'LY',
		countryName: 'Libya',
		unicodeFlag: '🇱🇾',
		dialCodeWithoutPlus: 218,
		dialCodeWithPlus: '+218',
		currencyCode: 'LYD',
		currencyName: 'Libyan Dinar',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	LCA: {
		isoAlpha2: 'LC',
		countryName: 'Saint Lucia',
		unicodeFlag: '🇱🇨',
		dialCodeWithoutPlus: 1758,
		dialCodeWithPlus: '+1758',
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	LIE: {
		isoAlpha2: 'LI',
		countryName: 'Liechtenstein',
		unicodeFlag: '🇱🇮',
		dialCodeWithoutPlus: 423,
		dialCodeWithPlus: '+423',
		currencyCode: 'CHF',
		currencyName: 'Swiss Franc',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	LKA: {
		isoAlpha2: 'LK',
		countryName: 'Sri Lanka',
		unicodeFlag: '🇱🇰',
		dialCodeWithoutPlus: 94,
		dialCodeWithPlus: '+94',
		currencyCode: 'LKR',
		currencyName: 'Rupee',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	LSO: {
		isoAlpha2: 'LS',
		countryName: 'Lesotho',
		unicodeFlag: '🇱🇸',
		dialCodeWithoutPlus: 266,
		dialCodeWithPlus: '+266',
		currencyCode: 'LSL',
		currencyName: 'Loti',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	LTU: {
		isoAlpha2: 'LT',
		countryName: 'Lithuania',
		unicodeFlag: '🇱🇹',
		dialCodeWithoutPlus: 370,
		dialCodeWithPlus: '+370',
		currencyCode: 'LTL',
		currencyName: 'Lita',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	LUX: {
		isoAlpha2: 'LU',
		countryName: 'Luxembourg',
		unicodeFlag: '🇱🇺',
		dialCodeWithoutPlus: 352,
		dialCodeWithPlus: '+352',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	LVA: {
		isoAlpha2: 'LV',
		countryName: 'Latvia',
		unicodeFlag: '🇱🇻',
		dialCodeWithoutPlus: 371,
		dialCodeWithPlus: '+371',
		currencyCode: 'LVL',
		currencyName: 'Lat',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	MAC: {
		isoAlpha2: 'MO',
		countryName: 'Macao',
		unicodeFlag: '🇲🇴',
		dialCodeWithoutPlus: 853,
		dialCodeWithPlus: '+853',
		currencyCode: 'MOP',
		currencyName: 'Pataca',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	MAF: {
		isoAlpha2: 'MF',
		countryName: 'Saint Martin',
		unicodeFlag: '🇲🇫',
		dialCodeWithoutPlus: 590,
		dialCodeWithPlus: '+590',
		currencyCode: 'ANG',
		currencyName: 'Netherlands Antillean guilder',
		continentCode: 'NA',
		continentName: 'North America'
	},
	MAR: {
		isoAlpha2: 'MA',
		countryName: 'Morocco',
		unicodeFlag: '🇲🇦',
		dialCodeWithoutPlus: 212,
		dialCodeWithPlus: '+212',
		currencyCode: 'MAD',
		currencyName: 'Dirham',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	MCO: {
		isoAlpha2: 'MC',
		countryName: 'Monaco',
		unicodeFlag: '🇲🇨',
		dialCodeWithoutPlus: 377,
		dialCodeWithPlus: '+377',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	MDA: {
		isoAlpha2: 'MD',
		countryName: 'Moldova',
		unicodeFlag: '🇲🇩',
		dialCodeWithoutPlus: 373,
		dialCodeWithPlus: '+373',
		currencyCode: 'MDL',
		currencyName: 'Leu',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	MDG: {
		isoAlpha2: 'MG',
		countryName: 'Madagascar',
		unicodeFlag: '🇲🇬',
		dialCodeWithoutPlus: 261,
		dialCodeWithPlus: '+261',
		currencyCode: 'MGA',
		currencyName: 'Malagasy Franc',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	MDV: {
		isoAlpha2: 'MV',
		countryName: 'Maldives',
		unicodeFlag: '🇲🇻',
		dialCodeWithoutPlus: 960,
		dialCodeWithPlus: '+960',
		currencyCode: 'MVR',
		currencyName: 'Rufiyaa',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	MEX: {
		isoAlpha2: 'MX',
		countryName: 'Mexico',
		unicodeFlag: '🇲🇽',
		dialCodeWithoutPlus: 52,
		dialCodeWithPlus: '+52',
		currencyCode: 'MXN',
		currencyName: 'Peso',
		continentCode: 'NA',
		continentName: 'North America'
	},
	MHL: {
		isoAlpha2: 'MH',
		countryName: 'Marshall Islands',
		unicodeFlag: '🇲🇭',
		dialCodeWithoutPlus: 692,
		dialCodeWithPlus: '+692',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	MKD: {
		isoAlpha2: 'MK',
		countryName: 'North Macedonia',
		unicodeFlag: '🇲🇰',
		dialCodeWithoutPlus: 389,
		dialCodeWithPlus: '+389',
		currencyCode: 'MKD',
		currencyName: 'Denar',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	MLI: {
		isoAlpha2: 'ML',
		countryName: 'Mali',
		unicodeFlag: '🇲🇱',
		dialCodeWithoutPlus: 223,
		dialCodeWithPlus: '+223',
		currencyCode: 'XOF',
		currencyName: 'CFA Franc BCEAO',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	MLT: {
		isoAlpha2: 'MT',
		countryName: 'Malta',
		unicodeFlag: '🇲🇹',
		dialCodeWithoutPlus: 356,
		dialCodeWithPlus: '+356',
		currencyCode: 'MTL',
		currencyName: 'Maltese Lira',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	MMR: {
		isoAlpha2: 'MM',
		countryName: 'Myanmar',
		unicodeFlag: '🇲🇲',
		dialCodeWithoutPlus: 95,
		dialCodeWithPlus: '+95',
		currencyCode: 'MMK',
		currencyName: 'Kyat',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	MNE: {
		isoAlpha2: 'ME',
		countryName: 'Montenegro',
		unicodeFlag: '🇲🇪',
		dialCodeWithoutPlus: 382,
		dialCodeWithPlus: '+382',
		currencyCode: 'EUR',
		currencyName: 'Euro',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	MNG: {
		isoAlpha2: 'MN',
		countryName: 'Mongolia',
		unicodeFlag: '🇲🇳',
		dialCodeWithoutPlus: 976,
		dialCodeWithPlus: '+976',
		currencyCode: 'MNT',
		currencyName: 'Tugrik',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	MNP: {
		isoAlpha2: 'MP',
		countryName: 'Northern Mariana Islands',
		unicodeFlag: '🇲🇵',
		dialCodeWithoutPlus: 1670,
		dialCodeWithPlus: '+1670',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	MOZ: {
		isoAlpha2: 'MZ',
		countryName: 'Mozambique',
		unicodeFlag: '🇲🇿',
		dialCodeWithoutPlus: 258,
		dialCodeWithPlus: '+258',
		currencyCode: 'MZN',
		currencyName: 'Metical',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	MRT: {
		isoAlpha2: 'MR',
		countryName: 'Mauritania',
		unicodeFlag: '🇲🇷',
		dialCodeWithoutPlus: 222,
		dialCodeWithPlus: '+222',
		currencyCode: 'MRO',
		currencyName: 'Ouguiya',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	MSR: {
		isoAlpha2: 'MS',
		countryName: 'Montserrat',
		unicodeFlag: '🇲🇸',
		dialCodeWithoutPlus: 1664,
		dialCodeWithPlus: '+1664',
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	MTQ: {
		isoAlpha2: 'MQ',
		countryName: 'Martinique',
		unicodeFlag: '🇲🇶',
		dialCodeWithoutPlus: 596,
		dialCodeWithPlus: '+596',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'NA',
		continentName: 'North America'
	},
	MUS: {
		isoAlpha2: 'MU',
		countryName: 'Mauritius',
		unicodeFlag: '🇲🇺',
		dialCodeWithoutPlus: 230,
		dialCodeWithPlus: '+230',
		currencyCode: 'MUR',
		currencyName: 'Mauritian Rupee',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	MWI: {
		isoAlpha2: 'MW',
		countryName: 'Malawi',
		unicodeFlag: '🇲🇼',
		dialCodeWithoutPlus: 265,
		dialCodeWithPlus: '+265',
		currencyCode: 'MWK',
		currencyName: 'Malawian Kwacha',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	MYS: {
		isoAlpha2: 'MY',
		countryName: 'Malaysia',
		unicodeFlag: '🇲🇾',
		dialCodeWithoutPlus: 60,
		dialCodeWithPlus: '+60',
		currencyCode: 'MYR',
		currencyName: 'Ringgit',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	MYT: {
		isoAlpha2: 'YT',
		countryName: 'Mayotte',
		unicodeFlag: '🇾🇹',
		dialCodeWithoutPlus: 262,
		dialCodeWithPlus: '+262',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	NAM: {
		isoAlpha2: 'NA',
		countryName: 'Namibia',
		unicodeFlag: '🇳🇦',
		dialCodeWithoutPlus: 264,
		dialCodeWithPlus: '+264',
		currencyCode: 'NAD',
		currencyName: 'Dollar',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	NCL: {
		isoAlpha2: 'NC',
		countryName: 'New Caledonia',
		unicodeFlag: '🇳🇨',
		dialCodeWithoutPlus: 687,
		dialCodeWithPlus: '+687',
		currencyCode: 'XPF',
		currencyName: 'CFP Franc',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	NER: {
		isoAlpha2: 'NE',
		countryName: 'Niger',
		unicodeFlag: '🇳🇪',
		dialCodeWithoutPlus: 227,
		dialCodeWithPlus: '+227',
		currencyCode: 'XOF',
		currencyName: 'CFA Franc BCEAO',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	NFK: {
		isoAlpha2: 'NF',
		countryName: 'Norfolk Island',
		unicodeFlag: '🇳🇫',
		dialCodeWithoutPlus: 672,
		dialCodeWithPlus: '+672',
		currencyCode: 'AUD',
		currencyName: 'Australian Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	NGA: {
		isoAlpha2: 'NG',
		countryName: 'Nigeria',
		unicodeFlag: '🇳🇬',
		dialCodeWithoutPlus: 234,
		dialCodeWithPlus: '+234',
		currencyCode: 'NGN',
		currencyName: 'Naira',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	NIC: {
		isoAlpha2: 'NI',
		countryName: 'Nicaragua',
		unicodeFlag: '🇳🇮',
		dialCodeWithoutPlus: 505,
		dialCodeWithPlus: '+505',
		currencyCode: 'NIO',
		currencyName: 'Cordoba Oro',
		continentCode: 'NA',
		continentName: 'North America'
	},
	NIU: {
		isoAlpha2: 'NU',
		countryName: 'Niue',
		unicodeFlag: '🇳🇺',
		dialCodeWithoutPlus: 683,
		dialCodeWithPlus: '+683',
		currencyCode: 'NZD',
		currencyName: 'New Zealand Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	NLD: {
		isoAlpha2: 'NL',
		countryName: 'Netherlands',
		unicodeFlag: '🇳🇱',
		dialCodeWithoutPlus: 31,
		dialCodeWithPlus: '+31',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	NOR: {
		isoAlpha2: 'NO',
		countryName: 'Norway',
		unicodeFlag: '🇳🇴',
		dialCodeWithoutPlus: 47,
		dialCodeWithPlus: '+47',
		currencyCode: 'NOK',
		currencyName: 'Norwegian Krone',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	NPL: {
		isoAlpha2: 'NP',
		countryName: 'Nepal',
		unicodeFlag: '🇳🇵',
		dialCodeWithoutPlus: 977,
		dialCodeWithPlus: '+977',
		currencyCode: 'NPR',
		currencyName: 'Nepalese Rupee',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	NRU: {
		isoAlpha2: 'NR',
		countryName: 'Nauru',
		unicodeFlag: '🇳🇷',
		dialCodeWithoutPlus: 674,
		dialCodeWithPlus: '+674',
		currencyCode: 'AUD',
		currencyName: 'Australian Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	NZL: {
		isoAlpha2: 'NZ',
		countryName: 'New Zealand',
		unicodeFlag: '🇳🇿',
		dialCodeWithoutPlus: 64,
		dialCodeWithPlus: '+64',
		currencyCode: 'NZD',
		currencyName: 'New Zealand Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	OMN: {
		isoAlpha2: 'OM',
		countryName: 'Oman',
		unicodeFlag: '🇴🇲',
		dialCodeWithoutPlus: 968,
		dialCodeWithPlus: '+968',
		currencyCode: 'OMR',
		currencyName: 'Sul Rial',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	PAK: {
		isoAlpha2: 'PK',
		countryName: 'Pakistan',
		unicodeFlag: '🇵🇰',
		dialCodeWithoutPlus: 92,
		dialCodeWithPlus: '+92',
		currencyCode: 'PKR',
		currencyName: 'Rupee',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	PAN: {
		isoAlpha2: 'PA',
		countryName: 'Panama',
		unicodeFlag: '🇵🇦',
		dialCodeWithoutPlus: 507,
		dialCodeWithPlus: '+507',
		currencyCode: 'PAB',
		currencyName: 'Balboa',
		continentCode: 'NA',
		continentName: 'North America'
	},
	PCN: {
		isoAlpha2: 'PN',
		countryName: 'Pitcairn',
		unicodeFlag: '🇵🇳',
		dialCodeWithoutPlus: 870,
		dialCodeWithPlus: '+870',
		currencyCode: 'NZD',
		currencyName: 'New Zealand Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	PER: {
		isoAlpha2: 'PE',
		countryName: 'Peru',
		unicodeFlag: '🇵🇪',
		dialCodeWithoutPlus: 51,
		dialCodeWithPlus: '+51',
		currencyCode: 'PEN',
		currencyName: 'Nuevo Sol',
		continentCode: 'SA',
		continentName: 'South America'
	},
	PHL: {
		isoAlpha2: 'PH',
		countryName: 'Philippines',
		unicodeFlag: '🇵🇭',
		dialCodeWithoutPlus: 63,
		dialCodeWithPlus: '+63',
		currencyCode: 'PHP',
		currencyName: 'Peso',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	PLW: {
		isoAlpha2: 'PW',
		countryName: 'Palau',
		unicodeFlag: '🇵🇼',
		dialCodeWithoutPlus: 680,
		dialCodeWithPlus: '+680',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	PNG: {
		isoAlpha2: 'PG',
		countryName: 'Papua New Guinea',
		unicodeFlag: '🇵🇬',
		dialCodeWithoutPlus: 675,
		dialCodeWithPlus: '+675',
		currencyCode: 'PGK',
		currencyName: 'Kina',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	POL: {
		isoAlpha2: 'PL',
		countryName: 'Poland',
		unicodeFlag: '🇵🇱',
		dialCodeWithoutPlus: 48,
		dialCodeWithPlus: '+48',
		currencyCode: 'PLN',
		currencyName: 'Zloty',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	PRI: {
		isoAlpha2: 'PR',
		countryName: 'Puerto Rico',
		unicodeFlag: '🇵🇷',
		dialCodeWithoutPlus: 1,
		dialCodeWithPlus: '+1',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'NA',
		continentName: 'North America'
	},
	PRK: {
		isoAlpha2: 'KP',
		countryName: 'North Korea',
		unicodeFlag: '🇰🇵',
		dialCodeWithoutPlus: 850,
		dialCodeWithPlus: '+850',
		currencyCode: 'KPW',
		currencyName: 'Won',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	PRT: {
		isoAlpha2: 'PT',
		countryName: 'Portugal',
		unicodeFlag: '🇵🇹',
		dialCodeWithoutPlus: 351,
		dialCodeWithPlus: '+351',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	PRY: {
		isoAlpha2: 'PY',
		countryName: 'Paraguay',
		unicodeFlag: '🇵🇾',
		dialCodeWithoutPlus: 595,
		dialCodeWithPlus: '+595',
		currencyCode: 'PYG',
		currencyName: 'Guarani',
		continentCode: 'SA',
		continentName: 'South America'
	},
	PSE: {
		isoAlpha2: 'PS',
		countryName: 'Palestinian Territory',
		unicodeFlag: '🇵🇸',
		dialCodeWithoutPlus: 970,
		dialCodeWithPlus: '+970',
		currencyCode: 'JOD',
		currencyName: 'Jordanian dinar',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	PYF: {
		isoAlpha2: 'PF',
		countryName: 'French Polynesia',
		unicodeFlag: '🇵🇫',
		dialCodeWithoutPlus: 689,
		dialCodeWithPlus: '+689',
		currencyCode: 'XPF',
		currencyName: 'CFP Franc',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	QAT: {
		isoAlpha2: 'QA',
		countryName: 'Qatar',
		unicodeFlag: '🇶🇦',
		dialCodeWithoutPlus: 974,
		dialCodeWithPlus: '+974',
		currencyCode: 'QAR',
		currencyName: 'Rial',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	REU: {
		isoAlpha2: 'RE',
		countryName: 'Réunion',
		unicodeFlag: '🇷🇪',
		dialCodeWithoutPlus: 262,
		dialCodeWithPlus: '+262',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	ROU: {
		isoAlpha2: 'RO',
		countryName: 'Romania',
		unicodeFlag: '🇷🇴',
		dialCodeWithoutPlus: 40,
		dialCodeWithPlus: '+40',
		currencyCode: 'RON',
		currencyName: 'Leu',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	RUS: {
		isoAlpha2: 'RU',
		countryName: 'Russian Federation',
		unicodeFlag: '🇷🇺',
		dialCodeWithoutPlus: 7,
		dialCodeWithPlus: '+7',
		currencyCode: 'RUB',
		currencyName: 'Ruble',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	RWA: {
		isoAlpha2: 'RW',
		countryName: 'Rwanda',
		unicodeFlag: '🇷🇼',
		dialCodeWithoutPlus: 250,
		dialCodeWithPlus: '+250',
		currencyCode: 'RWF',
		currencyName: 'Rwanda Franc',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	SAU: {
		isoAlpha2: 'SA',
		countryName: 'Saudi Arabia',
		unicodeFlag: '🇸🇦',
		dialCodeWithoutPlus: 966,
		dialCodeWithPlus: '+966',
		currencyCode: 'SAR',
		currencyName: 'Riyal',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	SDN: {
		isoAlpha2: 'SD',
		countryName: 'Sudan',
		unicodeFlag: '🇸🇩',
		dialCodeWithoutPlus: 249,
		dialCodeWithPlus: '+249',
		currencyCode: 'SDG',
		currencyName: 'Dinar',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	SEN: {
		isoAlpha2: 'SN',
		countryName: 'Senegal',
		unicodeFlag: '🇸🇳',
		dialCodeWithoutPlus: 221,
		dialCodeWithPlus: '+221',
		currencyCode: 'XOF',
		currencyName: 'CFA Franc BCEAO',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	SGP: {
		isoAlpha2: 'SG',
		countryName: 'Singapore',
		unicodeFlag: '🇸🇬',
		dialCodeWithoutPlus: 65,
		dialCodeWithPlus: '+65',
		currencyCode: 'SGD',
		currencyName: 'Dollar',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	SGS: {
		isoAlpha2: 'GS',
		countryName: 'South Georgia and the South Sandwich Islands',
		unicodeFlag: '🇬🇸',
		dialCodeWithoutPlus: 500,
		dialCodeWithPlus: '+500',
		currencyCode: 'GBP',
		currencyName: 'Sterling',
		continentCode: 'AN',
		continentName: 'Antarctica'
	},
	SHN: {
		isoAlpha2: 'SH',
		countryName: 'Saint Helena, Ascension and Tristan da Cunha',
		unicodeFlag: '🇸🇭',
		dialCodeWithoutPlus: 290,
		dialCodeWithPlus: '+290',
		currencyCode: 'GBP',
		currencyName: 'Saint Helena pound',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	SJM: {
		isoAlpha2: 'SJ',
		countryName: 'Svalbard and Jan Mayen',
		unicodeFlag: '🇸🇯',
		dialCodeWithoutPlus: 47,
		dialCodeWithPlus: '+47',
		currencyCode: 'NOK',
		currencyName: 'Norwegian Krone',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	SLB: {
		isoAlpha2: 'SB',
		countryName: 'Solomon Islands',
		unicodeFlag: '🇸🇧',
		dialCodeWithoutPlus: 677,
		dialCodeWithPlus: '+677',
		currencyCode: 'SBD',
		currencyName: 'Solomon Islands Dollar',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	SLE: {
		isoAlpha2: 'SL',
		countryName: 'Sierra Leone',
		unicodeFlag: '🇸🇱',
		dialCodeWithoutPlus: 232,
		dialCodeWithPlus: '+232',
		currencyCode: 'SLL',
		currencyName: 'Leone',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	SLV: {
		isoAlpha2: 'SV',
		countryName: 'El Salvador',
		unicodeFlag: '🇸🇻',
		dialCodeWithoutPlus: 503,
		dialCodeWithPlus: '+503',
		currencyCode: 'SVC',
		currencyName: 'Salvadoran Colon',
		continentCode: 'NA',
		continentName: 'North America'
	},
	SMR: {
		isoAlpha2: 'SM',
		countryName: 'San Marino',
		unicodeFlag: '🇸🇲',
		dialCodeWithoutPlus: 378,
		dialCodeWithPlus: '+378',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	SOM: {
		isoAlpha2: 'SO',
		countryName: 'Somalia',
		unicodeFlag: '🇸🇴',
		dialCodeWithoutPlus: 252,
		dialCodeWithPlus: '+252',
		currencyCode: 'SOS',
		currencyName: 'Shilling',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	SPM: {
		isoAlpha2: 'PM',
		countryName: 'Saint Pierre and Miquelon',
		unicodeFlag: '🇵🇲',
		dialCodeWithoutPlus: 508,
		dialCodeWithPlus: '+508',
		currencyCode: 'EUR',
		currencyName: 'Euro',
		continentCode: 'NA',
		continentName: 'North America'
	},
	SRB: {
		isoAlpha2: 'RS',
		countryName: 'Serbia',
		unicodeFlag: '🇷🇸',
		dialCodeWithoutPlus: 381,
		dialCodeWithPlus: '+381',
		currencyCode: 'RSD',
		currencyName: 'Serbian dinar',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	SSD: {
		isoAlpha2: 'SS',
		countryName: 'South Sudan',
		unicodeFlag: '🇸🇸',
		dialCodeWithoutPlus: 211,
		dialCodeWithPlus: '+211',
		currencyCode: 'SSP',
		currencyName: 'South Sudanese pound',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	STP: {
		isoAlpha2: 'ST',
		countryName: 'Sao Tome and Principe',
		unicodeFlag: '🇸🇹',
		dialCodeWithoutPlus: 239,
		dialCodeWithPlus: '+239',
		currencyCode: 'STD',
		currencyName: 'Dobra',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	SUR: {
		isoAlpha2: 'SR',
		countryName: 'Suriname',
		unicodeFlag: '🇸🇷',
		dialCodeWithoutPlus: 597,
		dialCodeWithPlus: '+597',
		currencyCode: 'SRD',
		currencyName: 'Surinamese Guilder',
		continentCode: 'SA',
		continentName: 'South America'
	},
	SVK: {
		isoAlpha2: 'SK',
		countryName: 'Slovakia',
		unicodeFlag: '🇸🇰',
		dialCodeWithoutPlus: 421,
		dialCodeWithPlus: '+421',
		currencyCode: 'SKK',
		currencyName: 'Koruna',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	SVN: {
		isoAlpha2: 'SI',
		countryName: 'Slovenia',
		unicodeFlag: '🇸🇮',
		dialCodeWithoutPlus: 386,
		dialCodeWithPlus: '+386',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	SWE: {
		isoAlpha2: 'SE',
		countryName: 'Sweden',
		unicodeFlag: '🇸🇪',
		dialCodeWithoutPlus: 46,
		dialCodeWithPlus: '+46',
		currencyCode: 'SEK',
		currencyName: 'Krona',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	SWZ: {
		isoAlpha2: 'SZ',
		countryName: 'Eswatini',
		unicodeFlag: '🇸🇿',
		dialCodeWithoutPlus: 268,
		dialCodeWithPlus: '+268',
		currencyCode: 'SZL',
		currencyName: 'Lilangeni',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	SXM: {
		isoAlpha2: 'SX',
		countryName: 'Sint Maarten',
		unicodeFlag: '🇸🇽',
		dialCodeWithoutPlus: 1721,
		dialCodeWithPlus: '+1721',
		currencyCode: 'ANG',
		currencyName: 'Netherlands Antillean guilder',
		continentCode: 'NA',
		continentName: 'North America'
	},
	SYC: {
		isoAlpha2: 'SC',
		countryName: 'Seychelles',
		unicodeFlag: '🇸🇨',
		dialCodeWithoutPlus: 248,
		dialCodeWithPlus: '+248',
		currencyCode: 'SCR',
		currencyName: 'Rupee',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	SYR: {
		isoAlpha2: 'SY',
		countryName: 'Syrian Arab Republic',
		unicodeFlag: '🇸🇾',
		dialCodeWithoutPlus: 963,
		dialCodeWithPlus: '+963',
		currencyCode: 'SYP',
		currencyName: 'Syrian Pound',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	TCA: {
		isoAlpha2: 'TC',
		countryName: 'Turks and Caicos Islands',
		unicodeFlag: '🇹🇨',
		dialCodeWithoutPlus: 1649,
		dialCodeWithPlus: '+1649',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'NA',
		continentName: 'North America'
	},
	TCD: {
		isoAlpha2: 'TD',
		countryName: 'Chad',
		unicodeFlag: '🇹🇩',
		dialCodeWithoutPlus: 235,
		dialCodeWithPlus: '+235',
		currencyCode: 'XAF',
		currencyName: 'CFA Franc BEAC',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	TGO: {
		isoAlpha2: 'TG',
		countryName: 'Togo',
		unicodeFlag: '🇹🇬',
		dialCodeWithoutPlus: 228,
		dialCodeWithPlus: '+228',
		currencyCode: 'XOF',
		currencyName: 'CFA Franc BCEAO',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	THA: {
		isoAlpha2: 'TH',
		countryName: 'Thailand',
		unicodeFlag: '🇹🇭',
		dialCodeWithoutPlus: 66,
		dialCodeWithPlus: '+66',
		currencyCode: 'THB',
		currencyName: 'Baht',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	TJK: {
		isoAlpha2: 'TJ',
		countryName: 'Tajikistan',
		unicodeFlag: '🇹🇯',
		dialCodeWithoutPlus: 992,
		dialCodeWithPlus: '+992',
		currencyCode: 'TJS',
		currencyName: 'Tajikistan Ruble',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	TKL: {
		isoAlpha2: 'TK',
		countryName: 'Tokelau',
		unicodeFlag: '🇹🇰',
		dialCodeWithoutPlus: 690,
		dialCodeWithPlus: '+690',
		currencyCode: 'NZD',
		currencyName: 'New Zealand Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	TKM: {
		isoAlpha2: 'TM',
		countryName: 'Turkmenistan',
		unicodeFlag: '🇹🇲',
		dialCodeWithoutPlus: 993,
		dialCodeWithPlus: '+993',
		currencyCode: 'TMT',
		currencyName: 'Manat',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	TLS: {
		isoAlpha2: 'TL',
		countryName: 'East Timor',
		unicodeFlag: '🇹🇱',
		dialCodeWithoutPlus: 670,
		dialCodeWithPlus: '+670',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	TON: {
		isoAlpha2: 'TO',
		countryName: 'Tonga',
		unicodeFlag: '🇹🇴',
		dialCodeWithoutPlus: 676,
		dialCodeWithPlus: '+676',
		currencyCode: 'TOP',
		currencyName: 'PaÕanga',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	TTO: {
		isoAlpha2: 'TT',
		countryName: 'Trinidad and Tobago',
		unicodeFlag: '🇹🇹',
		dialCodeWithoutPlus: 1868,
		dialCodeWithPlus: '+1868',
		currencyCode: 'TTD',
		currencyName: 'Trinidad and Tobago Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	TUN: {
		isoAlpha2: 'TN',
		countryName: 'Tunisia',
		unicodeFlag: '🇹🇳',
		dialCodeWithoutPlus: 216,
		dialCodeWithPlus: '+216',
		currencyCode: 'TND',
		currencyName: 'Tunisian Dinar',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	TUR: {
		isoAlpha2: 'TR',
		countryName: 'Turkey',
		unicodeFlag: '🇹🇷',
		dialCodeWithoutPlus: 90,
		dialCodeWithPlus: '+90',
		currencyCode: 'TRY',
		currencyName: 'Lira',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	TUV: {
		isoAlpha2: 'TV',
		countryName: 'Tuvalu',
		unicodeFlag: '🇹🇻',
		dialCodeWithoutPlus: 688,
		dialCodeWithPlus: '+688',
		currencyCode: 'AUD',
		currencyName: 'Australian Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	TWN: {
		isoAlpha2: 'TW',
		countryName: 'Taiwan',
		unicodeFlag: '🇹🇼',
		dialCodeWithoutPlus: 886,
		dialCodeWithPlus: '+886',
		currencyCode: 'TWD',
		currencyName: 'Dollar',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	TZA: {
		isoAlpha2: 'TZ',
		countryName: 'Tanzania',
		unicodeFlag: '🇹🇿',
		dialCodeWithoutPlus: 255,
		dialCodeWithPlus: '+255',
		currencyCode: 'TZS',
		currencyName: 'Shilling',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	UGA: {
		isoAlpha2: 'UG',
		countryName: 'Uganda',
		unicodeFlag: '🇺🇬',
		dialCodeWithoutPlus: 256,
		dialCodeWithPlus: '+256',
		currencyCode: 'UGX',
		currencyName: 'Shilling',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	UKR: {
		isoAlpha2: 'UA',
		countryName: 'Ukraine',
		unicodeFlag: '🇺🇦',
		dialCodeWithoutPlus: 380,
		dialCodeWithPlus: '+380',
		currencyCode: 'UAH',
		currencyName: 'Hryvnia',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	URY: {
		isoAlpha2: 'UY',
		countryName: 'Uruguay',
		unicodeFlag: '🇺🇾',
		dialCodeWithoutPlus: 598,
		dialCodeWithPlus: '+598',
		currencyCode: 'UYU',
		currencyName: 'Peso',
		continentCode: 'SA',
		continentName: 'South America'
	},
	USA: {
		isoAlpha2: 'US',
		countryName: 'United States of America',
		unicodeFlag: '🇺🇸',
		dialCodeWithoutPlus: 1,
		dialCodeWithPlus: '+1',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'NA',
		continentName: 'North America'
	},
	UZB: {
		isoAlpha2: 'UZ',
		countryName: 'Uzbekistan',
		unicodeFlag: '🇺🇿',
		dialCodeWithoutPlus: 998,
		dialCodeWithPlus: '+998',
		currencyCode: 'UZS',
		currencyName: 'Som',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	VAT: {
		isoAlpha2: 'VA',
		countryName: 'Holy See',
		unicodeFlag: '🇻🇦',
		dialCodeWithoutPlus: 3906,
		dialCodeWithPlus: '+3906',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	VCT: {
		isoAlpha2: 'VC',
		countryName: 'Saint Vincent and the Grenadines',
		unicodeFlag: '🇻🇨',
		dialCodeWithoutPlus: 1784,
		dialCodeWithPlus: '+1784',
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	VEN: {
		isoAlpha2: 'VE',
		countryName: 'Venezuela',
		unicodeFlag: '🇻🇪',
		dialCodeWithoutPlus: 58,
		dialCodeWithPlus: '+58',
		currencyCode: 'VEF',
		currencyName: 'Bolivar',
		continentCode: 'SA',
		continentName: 'South America'
	},
	VGB: {
		isoAlpha2: 'VG',
		countryName: 'Virgin Islands (British)',
		unicodeFlag: '🇻🇬',
		dialCodeWithoutPlus: 1284,
		dialCodeWithPlus: '+1284',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'NA',
		continentName: 'North America'
	},
	VIR: {
		isoAlpha2: 'VI',
		countryName: 'Virgin Islands (U.S.)',
		unicodeFlag: '🇻🇮',
		dialCodeWithoutPlus: 1340,
		dialCodeWithPlus: '+1340',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'NA',
		continentName: 'North America'
	},
	VNM: {
		isoAlpha2: 'VN',
		countryName: 'Viet Nam',
		unicodeFlag: '🇻🇳',
		dialCodeWithoutPlus: 84,
		dialCodeWithPlus: '+84',
		currencyCode: 'VND',
		currencyName: 'Dong',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	VUT: {
		isoAlpha2: 'VU',
		countryName: 'Vanuatu',
		unicodeFlag: '🇻🇺',
		dialCodeWithoutPlus: 678,
		dialCodeWithPlus: '+678',
		currencyCode: 'VUV',
		currencyName: 'Vatu',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	WLF: {
		isoAlpha2: 'WF',
		countryName: 'Wallis and Futuna',
		unicodeFlag: '🇼🇫',
		dialCodeWithoutPlus: 681,
		dialCodeWithPlus: '+681',
		currencyCode: 'XPF',
		currencyName: 'CFP Franc',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	WSM: {
		isoAlpha2: 'WS',
		countryName: 'Samoa',
		unicodeFlag: '🇼🇸',
		dialCodeWithoutPlus: 685,
		dialCodeWithPlus: '+685',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	YEM: {
		isoAlpha2: 'YE',
		countryName: 'Yemen',
		unicodeFlag: '🇾🇪',
		dialCodeWithoutPlus: 967,
		dialCodeWithPlus: '+967',
		currencyCode: 'YER',
		currencyName: 'Rial',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	ZAF: {
		isoAlpha2: 'ZA',
		countryName: 'South Africa',
		unicodeFlag: '🇿🇦',
		dialCodeWithoutPlus: 27,
		dialCodeWithPlus: '+27',
		currencyCode: 'ZAR',
		currencyName: 'Rand',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	ZMB: {
		isoAlpha2: 'ZM',
		countryName: 'Zambia',
		unicodeFlag: '🇿🇲',
		dialCodeWithoutPlus: 260,
		dialCodeWithPlus: '+260',
		currencyCode: 'ZMK',
		currencyName: 'Kwacha',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	ZWE: {
		isoAlpha2: 'ZW',
		countryName: 'Zimbabwe',
		unicodeFlag: '🇿🇼',
		dialCodeWithoutPlus: 263,
		dialCodeWithPlus: '+263',
		currencyCode: 'ZWD',
		currencyName: 'Zimbabwe Dollar',
		continentCode: 'AF',
		continentName: 'Africa'
	}
};

module.exports.ISOAlpha3Mapping = Alpha3Mapping;

module.exports.isValidAlpha3Code = val => typeof val === 'string' && Alpha3Mapping[val] !== undefined;
