'use strict';

const Alpha2Mapping = {
	AW: {
		isoAlpha3: 'ABW',
		countryName: 'Aruba',
		unicodeFlag: '🇦🇼',
		dialCodeWithoutPlus: 297,
		dialCodeWithPlus: '+297',
		currencyCode: 'ANG',
		currencyName: 'Netherlands Antilles Guilder',
		continentCode: 'NA',
		continentName: 'North America'
	},
	AF: {
		isoAlpha3: 'AFG',
		countryName: 'Afghanistan',
		unicodeFlag: '🇦🇫',
		dialCodeWithoutPlus: 93,
		dialCodeWithPlus: '+93',
		currencyCode: 'AFN',
		currencyName: 'Afghani',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	AO: {
		isoAlpha3: 'AGO',
		countryName: 'Angola',
		unicodeFlag: '🇦🇴',
		dialCodeWithoutPlus: 244,
		dialCodeWithPlus: '+244',
		currencyCode: 'AOA',
		currencyName: 'Angolan kwanza',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	AI: {
		isoAlpha3: 'AIA',
		countryName: 'Anguilla',
		unicodeFlag: '🇦🇮',
		dialCodeWithoutPlus: 1264,
		dialCodeWithPlus: '+1264',
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	AX: {
		isoAlpha3: 'ALA',
		countryName: 'Aland Islands',
		unicodeFlag: '🇦🇽',
		dialCodeWithoutPlus: 358,
		dialCodeWithPlus: '+358',
		currencyCode: 'EUR',
		currencyName: 'Euro',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	AL: {
		isoAlpha3: 'ALB',
		countryName: 'Albania',
		unicodeFlag: '🇦🇱',
		dialCodeWithoutPlus: 355,
		dialCodeWithPlus: '+355',
		currencyCode: 'ALL',
		currencyName: 'Lek',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	AD: {
		isoAlpha3: 'AND',
		countryName: 'Andorra',
		unicodeFlag: '🇦🇩',
		dialCodeWithoutPlus: 376,
		dialCodeWithPlus: '+376',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	AE: {
		isoAlpha3: 'ARE',
		countryName: 'United Arab Emirates',
		unicodeFlag: '🇦🇪',
		dialCodeWithoutPlus: 971,
		dialCodeWithPlus: '+971',
		currencyCode: 'AED',
		currencyName: 'Dirham',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	AR: {
		isoAlpha3: 'ARG',
		countryName: 'Argentina',
		unicodeFlag: '🇦🇷',
		dialCodeWithoutPlus: 54,
		dialCodeWithPlus: '+54',
		currencyCode: 'ARS',
		currencyName: 'Peso',
		continentCode: 'SA',
		continentName: 'South America'
	},
	AM: {
		isoAlpha3: 'ARM',
		countryName: 'Armenia',
		unicodeFlag: '🇦🇲',
		dialCodeWithoutPlus: 374,
		dialCodeWithPlus: '+374',
		currencyCode: 'AMD',
		currencyName: 'Dram',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	AS: {
		isoAlpha3: 'ASM',
		countryName: 'American Samoa',
		unicodeFlag: '🇦🇸',
		dialCodeWithoutPlus: 1684,
		dialCodeWithPlus: '+1684',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	AQ: {
		isoAlpha3: 'ATA',
		countryName: 'Antarctica',
		unicodeFlag: '🇦🇶',
		dialCodeWithoutPlus: 672,
		dialCodeWithPlus: '+672',
		currencyCode: 'AQD',
		currencyName: 'Antarctican dollar',
		continentCode: 'AN',
		continentName: 'Antarctica'
	},
	TF: {
		isoAlpha3: 'ATF',
		countryName: 'French Southern Territories',
		unicodeFlag: '🇹🇫',
		dialCodeWithoutPlus: 262,
		dialCodeWithPlus: '+262',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'AN',
		continentName: 'Antarctica'
	},
	AG: {
		isoAlpha3: 'ATG',
		countryName: 'Antigua and Barbuda',
		unicodeFlag: '🇦🇬',
		dialCodeWithoutPlus: 1268,
		dialCodeWithPlus: '+1268',
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	AU: {
		isoAlpha3: 'AUS',
		countryName: 'Australia',
		unicodeFlag: '🇦🇺',
		dialCodeWithoutPlus: 61,
		dialCodeWithPlus: '+61',
		currencyCode: 'AUD',
		currencyName: 'Australian Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	AT: {
		isoAlpha3: 'AUT',
		countryName: 'Austria',
		unicodeFlag: '🇦🇹',
		dialCodeWithoutPlus: 43,
		dialCodeWithPlus: '+43',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	AZ: {
		isoAlpha3: 'AZE',
		countryName: 'Azerbaijan',
		unicodeFlag: '🇦🇿',
		dialCodeWithoutPlus: 994,
		dialCodeWithPlus: '+994',
		currencyCode: 'AZN',
		currencyName: 'Manat',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	BI: {
		isoAlpha3: 'BDI',
		countryName: 'Burundi',
		unicodeFlag: '🇧🇮',
		dialCodeWithoutPlus: 257,
		dialCodeWithPlus: '+257',
		currencyCode: 'BIF',
		currencyName: 'Burundi Franc',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	BE: {
		isoAlpha3: 'BEL',
		countryName: 'Belgium',
		unicodeFlag: '🇧🇪',
		dialCodeWithoutPlus: 32,
		dialCodeWithPlus: '+32',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	BJ: {
		isoAlpha3: 'BEN',
		countryName: 'Benin',
		unicodeFlag: '🇧🇯',
		dialCodeWithoutPlus: 229,
		dialCodeWithPlus: '+229',
		currencyCode: 'XOF',
		currencyName: 'CFA Franc BCEAO',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	BQ: {
		isoAlpha3: 'BES',
		countryName: 'Bonaire, Sint Eustatius and Saba',
		unicodeFlag: '🇧🇶',
		dialCodeWithoutPlus: 599,
		dialCodeWithPlus: '+599',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'NA',
		continentName: 'North America'
	},
	BF: {
		isoAlpha3: 'BFA',
		countryName: 'Burkina Faso',
		unicodeFlag: '🇧🇫',
		dialCodeWithoutPlus: 226,
		dialCodeWithPlus: '+226',
		currencyCode: 'XOF',
		currencyName: 'CFA Franc BCEAO',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	BD: {
		isoAlpha3: 'BGD',
		countryName: 'Bangladesh',
		unicodeFlag: '🇧🇩',
		dialCodeWithoutPlus: 880,
		dialCodeWithPlus: '+880',
		currencyCode: 'BDT',
		currencyName: 'Taka',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	BG: {
		isoAlpha3: 'BGR',
		countryName: 'Bulgaria',
		unicodeFlag: '🇧🇬',
		dialCodeWithoutPlus: 359,
		dialCodeWithPlus: '+359',
		currencyCode: 'BGN',
		currencyName: 'Lev',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	BH: {
		isoAlpha3: 'BHR',
		countryName: 'Bahrain',
		unicodeFlag: '🇧🇭',
		dialCodeWithoutPlus: 973,
		dialCodeWithPlus: '+973',
		currencyCode: 'BHD',
		currencyName: 'Bahraini Dinar',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	BS: {
		isoAlpha3: 'BHS',
		countryName: 'Bahamas',
		unicodeFlag: '🇧🇸',
		dialCodeWithoutPlus: 1242,
		dialCodeWithPlus: '+1242',
		currencyCode: 'BSD',
		currencyName: 'Bahamian Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	BA: {
		isoAlpha3: 'BIH',
		countryName: 'Bosnia and Herzegovina',
		unicodeFlag: '🇧🇦',
		dialCodeWithoutPlus: 387,
		dialCodeWithPlus: '+387',
		currencyCode: 'BAM',
		currencyName: 'Bosnia and Herzegovina convertible mark',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	BL: {
		isoAlpha3: 'BLM',
		countryName: 'Saint Barthélemy',
		unicodeFlag: '🇧🇱',
		dialCodeWithoutPlus: 590,
		dialCodeWithPlus: '+590',
		currencyCode: 'EUR',
		currencyName: 'Euro',
		continentCode: 'NA',
		continentName: 'North America'
	},
	BY: {
		isoAlpha3: 'BLR',
		countryName: 'Belarus',
		unicodeFlag: '🇧🇾',
		dialCodeWithoutPlus: 375,
		dialCodeWithPlus: '+375',
		currencyCode: 'BYR',
		currencyName: 'Belarus Ruble',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	BZ: {
		isoAlpha3: 'BLZ',
		countryName: 'Belize',
		unicodeFlag: '🇧🇿',
		dialCodeWithoutPlus: 501,
		dialCodeWithPlus: '+501',
		currencyCode: 'BZD',
		currencyName: 'Belizean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	BM: {
		isoAlpha3: 'BMU',
		countryName: 'Bermuda',
		unicodeFlag: '🇧🇲',
		dialCodeWithoutPlus: 1441,
		dialCodeWithPlus: '+1441',
		currencyCode: 'BMD',
		currencyName: 'Bermudian Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	BO: {
		isoAlpha3: 'BOL',
		countryName: 'Bolivia (Plurinational State of)',
		unicodeFlag: '🇧🇴',
		dialCodeWithoutPlus: 591,
		dialCodeWithPlus: '+591',
		currencyCode: 'BOB',
		currencyName: 'Boliviano',
		continentCode: 'SA',
		continentName: 'South America'
	},
	BR: {
		isoAlpha3: 'BRA',
		countryName: 'Brazil',
		unicodeFlag: '🇧🇷',
		dialCodeWithoutPlus: 55,
		dialCodeWithPlus: '+55',
		currencyCode: 'BRL',
		currencyName: 'Brazil',
		continentCode: 'SA',
		continentName: 'South America'
	},
	BB: {
		isoAlpha3: 'BRB',
		countryName: 'Barbados',
		unicodeFlag: '🇧🇧',
		dialCodeWithoutPlus: 1246,
		dialCodeWithPlus: '+1246',
		currencyCode: 'BBD',
		currencyName: 'Barbadian Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	BN: {
		isoAlpha3: 'BRN',
		countryName: 'Brunei Darussalam',
		unicodeFlag: '🇧🇳',
		dialCodeWithoutPlus: 673,
		dialCodeWithPlus: '+673',
		currencyCode: 'BND',
		currencyName: 'Bruneian Dollar',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	BT: {
		isoAlpha3: 'BTN',
		countryName: 'Bhutan',
		unicodeFlag: '🇧🇹',
		dialCodeWithoutPlus: 975,
		dialCodeWithPlus: '+975',
		currencyCode: 'INR',
		currencyName: 'Indian Rupee',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	BV: {
		isoAlpha3: 'BVT',
		countryName: 'Bouvet Island',
		unicodeFlag: '🇧🇻',
		dialCodeWithoutPlus: 47,
		dialCodeWithPlus: '+47',
		currencyCode: 'NOK',
		currencyName: 'Norwegian Krone',
		continentCode: 'AN',
		continentName: 'Antarctica'
	},
	BW: {
		isoAlpha3: 'BWA',
		countryName: 'Botswana',
		unicodeFlag: '🇧🇼',
		dialCodeWithoutPlus: 267,
		dialCodeWithPlus: '+267',
		currencyCode: 'BWP',
		currencyName: 'Pula',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	CF: {
		isoAlpha3: 'CAF',
		countryName: 'Central African Republic',
		unicodeFlag: '🇨🇫',
		dialCodeWithoutPlus: 236,
		dialCodeWithPlus: '+236',
		currencyCode: 'XAF',
		currencyName: 'CFA Franc BEAC',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	CA: {
		isoAlpha3: 'CAN',
		countryName: 'Canada',
		unicodeFlag: '🇨🇦',
		dialCodeWithoutPlus: 1,
		dialCodeWithPlus: '+1',
		currencyCode: 'CAD',
		currencyName: 'Canadian Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	CC: {
		isoAlpha3: 'CCK',
		countryName: 'Cocos (Keeling) Islands',
		unicodeFlag: '🇨🇨',
		dialCodeWithoutPlus: 61,
		dialCodeWithPlus: '+61',
		currencyCode: 'AUD',
		currencyName: 'Australian Dollars',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	CH: {
		isoAlpha3: 'CHE',
		countryName: 'Switzerland',
		unicodeFlag: '🇨🇭',
		dialCodeWithoutPlus: 41,
		dialCodeWithPlus: '+41',
		currencyCode: 'CHF',
		currencyName: 'Swiss Franc',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	CL: {
		isoAlpha3: 'CHL',
		countryName: 'Chile',
		unicodeFlag: '🇨🇱',
		dialCodeWithoutPlus: 56,
		dialCodeWithPlus: '+56',
		currencyCode: 'CLP',
		currencyName: 'Chilean Peso',
		continentCode: 'SA',
		continentName: 'South America'
	},
	CN: {
		isoAlpha3: 'CHN',
		countryName: 'China',
		unicodeFlag: '🇨🇳',
		dialCodeWithoutPlus: 86,
		dialCodeWithPlus: '+86',
		currencyCode: 'CNY',
		currencyName: 'Yuan Renminbi',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	CI: {
		isoAlpha3: 'CIV',
		countryName: 'Côte d\'Ivoire',
		unicodeFlag: '🇨🇮',
		dialCodeWithoutPlus: 225,
		dialCodeWithPlus: '+225',
		currencyCode: 'XOF',
		currencyName: 'CFA Franc BCEAO',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	CM: {
		isoAlpha3: 'CMR',
		countryName: 'Cameroon',
		unicodeFlag: '🇨🇲',
		dialCodeWithoutPlus: 237,
		dialCodeWithPlus: '+237',
		currencyCode: 'XAF',
		currencyName: 'CFA Franc BEAC',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	CD: {
		isoAlpha3: 'COD',
		countryName: 'Democratic Republic of the Congo',
		unicodeFlag: '🇨🇩',
		dialCodeWithoutPlus: 243,
		dialCodeWithPlus: '+243',
		currencyCode: 'CDF',
		currencyName: 'Congolese Frank',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	CG: {
		isoAlpha3: 'COG',
		countryName: 'Republic of the Congo',
		unicodeFlag: '🇨🇬',
		dialCodeWithoutPlus: 242,
		dialCodeWithPlus: '+242',
		currencyCode: 'XAF',
		currencyName: 'CFA Franc BEAC',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	CK: {
		isoAlpha3: 'COK',
		countryName: 'Cook Islands',
		unicodeFlag: '🇨🇰',
		dialCodeWithoutPlus: 682,
		dialCodeWithPlus: '+682',
		currencyCode: 'NZD',
		currencyName: 'New Zealand Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	CO: {
		isoAlpha3: 'COL',
		countryName: 'Colombia',
		unicodeFlag: '🇨🇴',
		dialCodeWithoutPlus: 57,
		dialCodeWithPlus: '+57',
		currencyCode: 'COP',
		currencyName: 'Peso',
		continentCode: 'SA',
		continentName: 'South America'
	},
	KM: {
		isoAlpha3: 'COM',
		countryName: 'Comoros',
		unicodeFlag: '🇰🇲',
		dialCodeWithoutPlus: 269,
		dialCodeWithPlus: '+269',
		currencyCode: 'KMF',
		currencyName: 'Comoran Franc',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	CV: {
		isoAlpha3: 'CPV',
		countryName: 'Cabo Verde',
		unicodeFlag: '🇨🇻',
		dialCodeWithoutPlus: 238,
		dialCodeWithPlus: '+238',
		currencyCode: 'CVE',
		currencyName: 'Escudo',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	CR: {
		isoAlpha3: 'CRI',
		countryName: 'Costa Rica',
		unicodeFlag: '🇨🇷',
		dialCodeWithoutPlus: 506,
		dialCodeWithPlus: '+506',
		currencyCode: 'CRC',
		currencyName: 'Costa Rican Colon',
		continentCode: 'NA',
		continentName: 'North America'
	},
	CU: {
		isoAlpha3: 'CUB',
		countryName: 'Cuba',
		unicodeFlag: '🇨🇺',
		dialCodeWithoutPlus: 53,
		dialCodeWithPlus: '+53',
		currencyCode: 'CUP',
		currencyName: 'Cuban Peso',
		continentCode: 'NA',
		continentName: 'North America'
	},
	CW: {
		isoAlpha3: 'CUW',
		countryName: 'Curaçao',
		unicodeFlag: '🇨🇼',
		dialCodeWithoutPlus: 599,
		dialCodeWithPlus: '+599',
		currencyCode: 'ANG',
		currencyName: 'Netherlands Antillean guilder',
		continentCode: 'NA',
		continentName: 'North America'
	},
	CX: {
		isoAlpha3: 'CXR',
		countryName: 'Christmas Island',
		unicodeFlag: '🇨🇽',
		dialCodeWithoutPlus: 61,
		dialCodeWithPlus: '+61',
		currencyCode: 'AUD',
		currencyName: 'Australian Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	KY: {
		isoAlpha3: 'CYM',
		countryName: 'Cayman Islands',
		unicodeFlag: '🇰🇾',
		dialCodeWithoutPlus: 1345,
		dialCodeWithPlus: '+1345',
		currencyCode: 'KYD',
		currencyName: 'Caymanian Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	CY: {
		isoAlpha3: 'CYP',
		countryName: 'Cyprus',
		unicodeFlag: '🇨🇾',
		dialCodeWithoutPlus: 357,
		dialCodeWithPlus: '+357',
		currencyCode: 'CYP',
		currencyName: 'Cypriot Pound',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	CZ: {
		isoAlpha3: 'CZE',
		countryName: 'Czechia',
		unicodeFlag: '🇨🇿',
		dialCodeWithoutPlus: 420,
		dialCodeWithPlus: '+420',
		currencyCode: 'CZK',
		currencyName: 'Koruna',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	DE: {
		isoAlpha3: 'DEU',
		countryName: 'Germany',
		unicodeFlag: '🇩🇪',
		dialCodeWithoutPlus: 49,
		dialCodeWithPlus: '+49',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	DJ: {
		isoAlpha3: 'DJI',
		countryName: 'Djibouti',
		unicodeFlag: '🇩🇯',
		dialCodeWithoutPlus: 253,
		dialCodeWithPlus: '+253',
		currencyCode: 'DJF',
		currencyName: 'Djiboutian Franc',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	DM: {
		isoAlpha3: 'DMA',
		countryName: 'Dominica',
		unicodeFlag: '🇩🇲',
		dialCodeWithoutPlus: 1767,
		dialCodeWithPlus: '+1767',
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	DK: {
		isoAlpha3: 'DNK',
		countryName: 'Denmark',
		unicodeFlag: '🇩🇰',
		dialCodeWithoutPlus: 45,
		dialCodeWithPlus: '+45',
		currencyCode: 'DKK',
		currencyName: 'Danish Krone',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	DO: {
		isoAlpha3: 'DOM',
		countryName: 'Dominican Republic',
		unicodeFlag: '🇩🇴',
		dialCodeWithoutPlus: 1,
		dialCodeWithPlus: '+1',
		currencyCode: 'DOP',
		currencyName: 'Dominican Peso',
		continentCode: 'NA',
		continentName: 'North America'
	},
	DZ: {
		isoAlpha3: 'DZA',
		countryName: 'Algeria',
		unicodeFlag: '🇩🇿',
		dialCodeWithoutPlus: 213,
		dialCodeWithPlus: '+213',
		currencyCode: 'DZD',
		currencyName: 'Algerian Dinar',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	EC: {
		isoAlpha3: 'ECU',
		countryName: 'Ecuador',
		unicodeFlag: '🇪🇨',
		dialCodeWithoutPlus: 593,
		dialCodeWithPlus: '+593',
		currencyCode: 'ECS',
		currencyName: 'Sucre',
		continentCode: 'SA',
		continentName: 'South America'
	},
	EG: {
		isoAlpha3: 'EGY',
		countryName: 'Egypt',
		unicodeFlag: '🇪🇬',
		dialCodeWithoutPlus: 20,
		dialCodeWithPlus: '+20',
		currencyCode: 'EGP',
		currencyName: 'Egyptian Pound',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	ER: {
		isoAlpha3: 'ERI',
		countryName: 'Eritrea',
		unicodeFlag: '🇪🇷',
		dialCodeWithoutPlus: 291,
		dialCodeWithPlus: '+291',
		currencyCode: 'ETB',
		currencyName: 'Ethiopian Birr',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	EH: {
		isoAlpha3: 'ESH',
		countryName: 'Western Sahara',
		unicodeFlag: '🇪🇭',
		dialCodeWithoutPlus: 212,
		dialCodeWithPlus: '+212',
		currencyCode: 'MAD',
		currencyName: 'Dirham',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	ES: {
		isoAlpha3: 'ESP',
		countryName: 'Spain',
		unicodeFlag: '🇪🇸',
		dialCodeWithoutPlus: 34,
		dialCodeWithPlus: '+34',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	EE: {
		isoAlpha3: 'EST',
		countryName: 'Estonia',
		unicodeFlag: '🇪🇪',
		dialCodeWithoutPlus: 372,
		dialCodeWithPlus: '+372',
		currencyCode: 'EEK',
		currencyName: 'Estonian Kroon',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	ET: {
		isoAlpha3: 'ETH',
		countryName: 'Ethiopia',
		unicodeFlag: '🇪🇹',
		dialCodeWithoutPlus: 251,
		dialCodeWithPlus: '+251',
		currencyCode: 'ETB',
		currencyName: 'Ethiopian Birr',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	FI: {
		isoAlpha3: 'FIN',
		countryName: 'Finland',
		unicodeFlag: '🇫🇮',
		dialCodeWithoutPlus: 358,
		dialCodeWithPlus: '+358',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	FJ: {
		isoAlpha3: 'FJI',
		countryName: 'Fiji',
		unicodeFlag: '🇫🇯',
		dialCodeWithoutPlus: 679,
		dialCodeWithPlus: '+679',
		currencyCode: 'FJD',
		currencyName: 'Fijian Dollar',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	FK: {
		isoAlpha3: 'FLK',
		countryName: 'Falkland Islands (Malvinas)',
		unicodeFlag: '🇫🇰',
		dialCodeWithoutPlus: 500,
		dialCodeWithPlus: '+500',
		currencyCode: 'FKP',
		currencyName: 'Falkland Pound',
		continentCode: 'SA',
		continentName: 'South America'
	},
	FR: {
		isoAlpha3: 'FRA',
		countryName: 'France',
		unicodeFlag: '🇫🇷',
		dialCodeWithoutPlus: 33,
		dialCodeWithPlus: '+33',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	FO: {
		isoAlpha3: 'FRO',
		countryName: 'Faroe Islands',
		unicodeFlag: '🇫🇴',
		dialCodeWithoutPlus: 298,
		dialCodeWithPlus: '+298',
		currencyCode: 'DKK',
		currencyName: 'Danish Krone',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	FM: {
		isoAlpha3: 'FSM',
		countryName: 'Micronesia (Federated States of)',
		unicodeFlag: '🇫🇲',
		dialCodeWithoutPlus: 691,
		dialCodeWithPlus: '+691',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	GA: {
		isoAlpha3: 'GAB',
		countryName: 'Gabon',
		unicodeFlag: '🇬🇦',
		dialCodeWithoutPlus: 241,
		dialCodeWithPlus: '+241',
		currencyCode: 'XAF',
		currencyName: 'CFA Franc BEAC',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	GB: {
		isoAlpha3: 'GBR',
		countryName: 'United Kingdom of Great Britain and Northern Ireland',
		unicodeFlag: '🇬🇧',
		dialCodeWithoutPlus: 44,
		dialCodeWithPlus: '+44',
		currencyCode: 'GBP',
		currencyName: 'Sterling',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	GE: {
		isoAlpha3: 'GEO',
		countryName: 'Georgia',
		unicodeFlag: '🇬🇪',
		dialCodeWithoutPlus: 995,
		dialCodeWithPlus: '+995',
		currencyCode: 'GEL',
		currencyName: 'Lari',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	GG: {
		isoAlpha3: 'GGY',
		countryName: 'Guernsey',
		unicodeFlag: '🇬🇬',
		dialCodeWithoutPlus: 44,
		dialCodeWithPlus: '+44',
		currencyCode: 'GGP',
		currencyName: 'Guernsey pound',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	GH: {
		isoAlpha3: 'GHA',
		countryName: 'Ghana',
		unicodeFlag: '🇬🇭',
		dialCodeWithoutPlus: 233,
		dialCodeWithPlus: '+233',
		currencyCode: 'GHS',
		currencyName: 'Ghana cedi',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	GI: {
		isoAlpha3: 'GIB',
		countryName: 'Gibraltar',
		unicodeFlag: '🇬🇮',
		dialCodeWithoutPlus: 350,
		dialCodeWithPlus: '+350',
		currencyCode: 'GIP',
		currencyName: 'Gibraltar Pound',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	GN: {
		isoAlpha3: 'GIN',
		countryName: 'Guinea',
		unicodeFlag: '🇬🇳',
		dialCodeWithoutPlus: 224,
		dialCodeWithPlus: '+224',
		currencyCode: 'GNF',
		currencyName: 'Guinean Franc',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	GP: {
		isoAlpha3: 'GLP',
		countryName: 'Guadeloupe',
		unicodeFlag: '🇬🇵',
		dialCodeWithoutPlus: 590,
		dialCodeWithPlus: '+590',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'NA',
		continentName: 'North America'
	},
	GM: {
		isoAlpha3: 'GMB',
		countryName: 'Gambia',
		unicodeFlag: '🇬🇲',
		dialCodeWithoutPlus: 220,
		dialCodeWithPlus: '+220',
		currencyCode: 'GMD',
		currencyName: 'Dalasi',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	GW: {
		isoAlpha3: 'GNB',
		countryName: 'Guinea-Bissau',
		unicodeFlag: '🇬🇼',
		dialCodeWithoutPlus: 245,
		dialCodeWithPlus: '+245',
		currencyCode: 'XOF',
		currencyName: 'CFA Franc BCEAO',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	GQ: {
		isoAlpha3: 'GNQ',
		countryName: 'Equatorial Guinea',
		unicodeFlag: '🇬🇶',
		dialCodeWithoutPlus: 240,
		dialCodeWithPlus: '+240',
		currencyCode: 'XAF',
		currencyName: 'CFA Franc BEAC',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	GR: {
		isoAlpha3: 'GRC',
		countryName: 'Greece',
		unicodeFlag: '🇬🇷',
		dialCodeWithoutPlus: 30,
		dialCodeWithPlus: '+30',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	GD: {
		isoAlpha3: 'GRD',
		countryName: 'Grenada',
		unicodeFlag: '🇬🇩',
		dialCodeWithoutPlus: 1473,
		dialCodeWithPlus: '+1473',
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	GL: {
		isoAlpha3: 'GRL',
		countryName: 'Greenland',
		unicodeFlag: '🇬🇱',
		dialCodeWithoutPlus: 299,
		dialCodeWithPlus: '+299',
		currencyCode: 'DKK',
		currencyName: 'Danish Krone',
		continentCode: 'NA',
		continentName: 'North America'
	},
	GT: {
		isoAlpha3: 'GTM',
		countryName: 'Guatemala',
		unicodeFlag: '🇬🇹',
		dialCodeWithoutPlus: 502,
		dialCodeWithPlus: '+502',
		currencyCode: 'GTQ',
		currencyName: 'Quetzal',
		continentCode: 'NA',
		continentName: 'North America'
	},
	GF: {
		isoAlpha3: 'GUF',
		countryName: 'French Guiana',
		unicodeFlag: '🇬🇫',
		dialCodeWithoutPlus: 594,
		dialCodeWithPlus: '+594',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'SA',
		continentName: 'South America'
	},
	GU: {
		isoAlpha3: 'GUM',
		countryName: 'Guam',
		unicodeFlag: '🇬🇺',
		dialCodeWithoutPlus: 1671,
		dialCodeWithPlus: '+1671',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	GY: {
		isoAlpha3: 'GUY',
		countryName: 'Guyana',
		unicodeFlag: '🇬🇾',
		dialCodeWithoutPlus: 592,
		dialCodeWithPlus: '+592',
		currencyCode: 'GYD',
		currencyName: 'Guyanaese Dollar',
		continentCode: 'SA',
		continentName: 'South America'
	},
	HK: {
		isoAlpha3: 'HKG',
		countryName: 'Hong Kong',
		unicodeFlag: '🇭🇰',
		dialCodeWithoutPlus: 852,
		dialCodeWithPlus: '+852',
		currencyCode: 'HKD',
		currencyName: 'HKD',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	HM: {
		isoAlpha3: 'HMD',
		countryName: 'Heard Island and McDonald Islands',
		unicodeFlag: '🇭🇲',
		dialCodeWithoutPlus: 672,
		dialCodeWithPlus: '+672',
		currencyCode: 'AUD',
		currencyName: 'Australian Dollars',
		continentCode: 'AN',
		continentName: 'Antarctica'
	},
	HN: {
		isoAlpha3: 'HND',
		countryName: 'Honduras',
		unicodeFlag: '🇭🇳',
		dialCodeWithoutPlus: 504,
		dialCodeWithPlus: '+504',
		currencyCode: 'HNL',
		currencyName: 'Lempira',
		continentCode: 'NA',
		continentName: 'North America'
	},
	HR: {
		isoAlpha3: 'HRV',
		countryName: 'Croatia',
		unicodeFlag: '🇭🇷',
		dialCodeWithoutPlus: 385,
		dialCodeWithPlus: '+385',
		currencyCode: 'HRK',
		currencyName: 'Croatian Dinar',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	HT: {
		isoAlpha3: 'HTI',
		countryName: 'Haiti',
		unicodeFlag: '🇭🇹',
		dialCodeWithoutPlus: 509,
		dialCodeWithPlus: '+509',
		currencyCode: 'HTG',
		currencyName: 'Gourde',
		continentCode: 'NA',
		continentName: 'North America'
	},
	HU: {
		isoAlpha3: 'HUN',
		countryName: 'Hungary',
		unicodeFlag: '🇭🇺',
		dialCodeWithoutPlus: 36,
		dialCodeWithPlus: '+36',
		currencyCode: 'HUF',
		currencyName: 'Forint',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	ID: {
		isoAlpha3: 'IDN',
		countryName: 'Indonesia',
		unicodeFlag: '🇮🇩',
		dialCodeWithoutPlus: 62,
		dialCodeWithPlus: '+62',
		currencyCode: 'IDR',
		currencyName: 'Indonesian Rupiah',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	IM: {
		isoAlpha3: 'IMN',
		countryName: 'Isle of Man',
		unicodeFlag: '🇮🇲',
		dialCodeWithoutPlus: 44,
		dialCodeWithPlus: '+44',
		currencyCode: 'GBP',
		currencyName: 'Manx pound',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	IN: {
		isoAlpha3: 'IND',
		countryName: 'India',
		unicodeFlag: '🇮🇳',
		dialCodeWithoutPlus: 91,
		dialCodeWithPlus: '+91',
		currencyCode: 'INR',
		currencyName: 'Indian Rupee',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	IO: {
		isoAlpha3: 'IOT',
		countryName: 'British Indian Ocean Territory',
		unicodeFlag: '🇮🇴',
		dialCodeWithoutPlus: 246,
		dialCodeWithPlus: '+246',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	IE: {
		isoAlpha3: 'IRL',
		countryName: 'Ireland',
		unicodeFlag: '🇮🇪',
		dialCodeWithoutPlus: 353,
		dialCodeWithPlus: '+353',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	IR: {
		isoAlpha3: 'IRN',
		countryName: 'Iran',
		unicodeFlag: '🇮🇷',
		dialCodeWithoutPlus: 98,
		dialCodeWithPlus: '+98',
		currencyCode: 'IRR',
		currencyName: 'Iranian Rial',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	IQ: {
		isoAlpha3: 'IRQ',
		countryName: 'Iraq',
		unicodeFlag: '🇮🇶',
		dialCodeWithoutPlus: 964,
		dialCodeWithPlus: '+964',
		currencyCode: 'IQD',
		currencyName: 'Iraqi Dinar',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	IS: {
		isoAlpha3: 'ISL',
		countryName: 'Iceland',
		unicodeFlag: '🇮🇸',
		dialCodeWithoutPlus: 354,
		dialCodeWithPlus: '+354',
		currencyCode: 'ISK',
		currencyName: 'Icelandic Krona',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	IL: {
		isoAlpha3: 'ISR',
		countryName: 'Israel',
		unicodeFlag: '🇮🇱',
		dialCodeWithoutPlus: 972,
		dialCodeWithPlus: '+972',
		currencyCode: 'ILS',
		currencyName: 'Shekel',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	IT: {
		isoAlpha3: 'ITA',
		countryName: 'Italy',
		unicodeFlag: '🇮🇹',
		dialCodeWithoutPlus: 39,
		dialCodeWithPlus: '+39',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	JM: {
		isoAlpha3: 'JAM',
		countryName: 'Jamaica',
		unicodeFlag: '🇯🇲',
		dialCodeWithoutPlus: 1876,
		dialCodeWithPlus: '+1876',
		currencyCode: 'JMD',
		currencyName: 'Jamaican Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	JE: {
		isoAlpha3: 'JEY',
		countryName: 'Jersey',
		unicodeFlag: '🇯🇪',
		dialCodeWithoutPlus: 44,
		dialCodeWithPlus: '+44',
		currencyCode: 'GBP',
		currencyName: 'Sterling',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	JO: {
		isoAlpha3: 'JOR',
		countryName: 'Jordan',
		unicodeFlag: '🇯🇴',
		dialCodeWithoutPlus: 962,
		dialCodeWithPlus: '+962',
		currencyCode: 'JOD',
		currencyName: 'Jordanian Dinar',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	JP: {
		isoAlpha3: 'JPN',
		countryName: 'Japan',
		unicodeFlag: '🇯🇵',
		dialCodeWithoutPlus: 81,
		dialCodeWithPlus: '+81',
		currencyCode: 'JPY',
		currencyName: 'Japanese Yen',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	KZ: {
		isoAlpha3: 'KAZ',
		countryName: 'Kazakhstan',
		unicodeFlag: '🇰🇿',
		dialCodeWithoutPlus: 7,
		dialCodeWithPlus: '+7',
		currencyCode: 'KZT',
		currencyName: 'Tenge',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	KE: {
		isoAlpha3: 'KEN',
		countryName: 'Kenya',
		unicodeFlag: '🇰🇪',
		dialCodeWithoutPlus: 254,
		dialCodeWithPlus: '+254',
		currencyCode: 'KES',
		currencyName: 'Kenyan Shilling',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	KG: {
		isoAlpha3: 'KGZ',
		countryName: 'Kyrgyzstan',
		unicodeFlag: '🇰🇬',
		dialCodeWithoutPlus: 996,
		dialCodeWithPlus: '+996',
		currencyCode: 'KGS',
		currencyName: 'Som',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	KH: {
		isoAlpha3: 'KHM',
		countryName: 'Cambodia',
		unicodeFlag: '🇰🇭',
		dialCodeWithoutPlus: 855,
		dialCodeWithPlus: '+855',
		currencyCode: 'KHR',
		currencyName: 'Riel',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	KI: {
		isoAlpha3: 'KIR',
		countryName: 'Kiribati',
		unicodeFlag: '🇰🇮',
		dialCodeWithoutPlus: 686,
		dialCodeWithPlus: '+686',
		currencyCode: 'AUD',
		currencyName: 'Australian Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	KN: {
		isoAlpha3: 'KNA',
		countryName: 'Saint Kitts and Nevis',
		unicodeFlag: '🇰🇳',
		dialCodeWithoutPlus: 1869,
		dialCodeWithPlus: '+1869',
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	KR: {
		isoAlpha3: 'KOR',
		countryName: 'South Korea',
		unicodeFlag: '🇰🇷',
		dialCodeWithoutPlus: 82,
		dialCodeWithPlus: '+82',
		currencyCode: 'KRW',
		currencyName: 'Won',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	KW: {
		isoAlpha3: 'KWT',
		countryName: 'Kuwait',
		unicodeFlag: '🇰🇼',
		dialCodeWithoutPlus: 965,
		dialCodeWithPlus: '+965',
		currencyCode: 'KWD',
		currencyName: 'Kuwaiti Dinar',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	LA: {
		isoAlpha3: 'LAO',
		countryName: 'Laos',
		unicodeFlag: '🇱🇦',
		dialCodeWithoutPlus: 856,
		dialCodeWithPlus: '+856',
		currencyCode: 'LAK',
		currencyName: 'Kip',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	LB: {
		isoAlpha3: 'LBN',
		countryName: 'Lebanon',
		unicodeFlag: '🇱🇧',
		dialCodeWithoutPlus: 961,
		dialCodeWithPlus: '+961',
		currencyCode: 'LBP',
		currencyName: 'Lebanese Pound',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	LR: {
		isoAlpha3: 'LBR',
		countryName: 'Liberia',
		unicodeFlag: '🇱🇷',
		dialCodeWithoutPlus: 231,
		dialCodeWithPlus: '+231',
		currencyCode: 'LRD',
		currencyName: 'Liberian Dollar',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	LY: {
		isoAlpha3: 'LBY',
		countryName: 'Libya',
		unicodeFlag: '🇱🇾',
		dialCodeWithoutPlus: 218,
		dialCodeWithPlus: '+218',
		currencyCode: 'LYD',
		currencyName: 'Libyan Dinar',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	LC: {
		isoAlpha3: 'LCA',
		countryName: 'Saint Lucia',
		unicodeFlag: '🇱🇨',
		dialCodeWithoutPlus: 1758,
		dialCodeWithPlus: '+1758',
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	LI: {
		isoAlpha3: 'LIE',
		countryName: 'Liechtenstein',
		unicodeFlag: '🇱🇮',
		dialCodeWithoutPlus: 423,
		dialCodeWithPlus: '+423',
		currencyCode: 'CHF',
		currencyName: 'Swiss Franc',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	LK: {
		isoAlpha3: 'LKA',
		countryName: 'Sri Lanka',
		unicodeFlag: '🇱🇰',
		dialCodeWithoutPlus: 94,
		dialCodeWithPlus: '+94',
		currencyCode: 'LKR',
		currencyName: 'Rupee',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	LS: {
		isoAlpha3: 'LSO',
		countryName: 'Lesotho',
		unicodeFlag: '🇱🇸',
		dialCodeWithoutPlus: 266,
		dialCodeWithPlus: '+266',
		currencyCode: 'LSL',
		currencyName: 'Loti',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	LT: {
		isoAlpha3: 'LTU',
		countryName: 'Lithuania',
		unicodeFlag: '🇱🇹',
		dialCodeWithoutPlus: 370,
		dialCodeWithPlus: '+370',
		currencyCode: 'LTL',
		currencyName: 'Lita',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	LU: {
		isoAlpha3: 'LUX',
		countryName: 'Luxembourg',
		unicodeFlag: '🇱🇺',
		dialCodeWithoutPlus: 352,
		dialCodeWithPlus: '+352',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	LV: {
		isoAlpha3: 'LVA',
		countryName: 'Latvia',
		unicodeFlag: '🇱🇻',
		dialCodeWithoutPlus: 371,
		dialCodeWithPlus: '+371',
		currencyCode: 'LVL',
		currencyName: 'Lat',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	MO: {
		isoAlpha3: 'MAC',
		countryName: 'Macao',
		unicodeFlag: '🇲🇴',
		dialCodeWithoutPlus: 853,
		dialCodeWithPlus: '+853',
		currencyCode: 'MOP',
		currencyName: 'Pataca',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	MF: {
		isoAlpha3: 'MAF',
		countryName: 'Saint Martin',
		unicodeFlag: '🇲🇫',
		dialCodeWithoutPlus: 590,
		dialCodeWithPlus: '+590',
		currencyCode: 'ANG',
		currencyName: 'Netherlands Antillean guilder',
		continentCode: 'NA',
		continentName: 'North America'
	},
	MA: {
		isoAlpha3: 'MAR',
		countryName: 'Morocco',
		unicodeFlag: '🇲🇦',
		dialCodeWithoutPlus: 212,
		dialCodeWithPlus: '+212',
		currencyCode: 'MAD',
		currencyName: 'Dirham',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	MC: {
		isoAlpha3: 'MCO',
		countryName: 'Monaco',
		unicodeFlag: '🇲🇨',
		dialCodeWithoutPlus: 377,
		dialCodeWithPlus: '+377',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	MD: {
		isoAlpha3: 'MDA',
		countryName: 'Moldova',
		unicodeFlag: '🇲🇩',
		dialCodeWithoutPlus: 373,
		dialCodeWithPlus: '+373',
		currencyCode: 'MDL',
		currencyName: 'Leu',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	MG: {
		isoAlpha3: 'MDG',
		countryName: 'Madagascar',
		unicodeFlag: '🇲🇬',
		dialCodeWithoutPlus: 261,
		dialCodeWithPlus: '+261',
		currencyCode: 'MGA',
		currencyName: 'Malagasy Franc',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	MV: {
		isoAlpha3: 'MDV',
		countryName: 'Maldives',
		unicodeFlag: '🇲🇻',
		dialCodeWithoutPlus: 960,
		dialCodeWithPlus: '+960',
		currencyCode: 'MVR',
		currencyName: 'Rufiyaa',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	MX: {
		isoAlpha3: 'MEX',
		countryName: 'Mexico',
		unicodeFlag: '🇲🇽',
		dialCodeWithoutPlus: 52,
		dialCodeWithPlus: '+52',
		currencyCode: 'MXN',
		currencyName: 'Peso',
		continentCode: 'NA',
		continentName: 'North America'
	},
	MH: {
		isoAlpha3: 'MHL',
		countryName: 'Marshall Islands',
		unicodeFlag: '🇲🇭',
		dialCodeWithoutPlus: 692,
		dialCodeWithPlus: '+692',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	MK: {
		isoAlpha3: 'MKD',
		countryName: 'North Macedonia',
		unicodeFlag: '🇲🇰',
		dialCodeWithoutPlus: 389,
		dialCodeWithPlus: '+389',
		currencyCode: 'MKD',
		currencyName: 'Denar',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	ML: {
		isoAlpha3: 'MLI',
		countryName: 'Mali',
		unicodeFlag: '🇲🇱',
		dialCodeWithoutPlus: 223,
		dialCodeWithPlus: '+223',
		currencyCode: 'XOF',
		currencyName: 'CFA Franc BCEAO',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	MT: {
		isoAlpha3: 'MLT',
		countryName: 'Malta',
		unicodeFlag: '🇲🇹',
		dialCodeWithoutPlus: 356,
		dialCodeWithPlus: '+356',
		currencyCode: 'MTL',
		currencyName: 'Maltese Lira',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	MM: {
		isoAlpha3: 'MMR',
		countryName: 'Myanmar',
		unicodeFlag: '🇲🇲',
		dialCodeWithoutPlus: 95,
		dialCodeWithPlus: '+95',
		currencyCode: 'MMK',
		currencyName: 'Kyat',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	ME: {
		isoAlpha3: 'MNE',
		countryName: 'Montenegro',
		unicodeFlag: '🇲🇪',
		dialCodeWithoutPlus: 382,
		dialCodeWithPlus: '+382',
		currencyCode: 'EUR',
		currencyName: 'Euro',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	MN: {
		isoAlpha3: 'MNG',
		countryName: 'Mongolia',
		unicodeFlag: '🇲🇳',
		dialCodeWithoutPlus: 976,
		dialCodeWithPlus: '+976',
		currencyCode: 'MNT',
		currencyName: 'Tugrik',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	MP: {
		isoAlpha3: 'MNP',
		countryName: 'Northern Mariana Islands',
		unicodeFlag: '🇲🇵',
		dialCodeWithoutPlus: 1670,
		dialCodeWithPlus: '+1670',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	MZ: {
		isoAlpha3: 'MOZ',
		countryName: 'Mozambique',
		unicodeFlag: '🇲🇿',
		dialCodeWithoutPlus: 258,
		dialCodeWithPlus: '+258',
		currencyCode: 'MZN',
		currencyName: 'Metical',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	MR: {
		isoAlpha3: 'MRT',
		countryName: 'Mauritania',
		unicodeFlag: '🇲🇷',
		dialCodeWithoutPlus: 222,
		dialCodeWithPlus: '+222',
		currencyCode: 'MRO',
		currencyName: 'Ouguiya',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	MS: {
		isoAlpha3: 'MSR',
		countryName: 'Montserrat',
		unicodeFlag: '🇲🇸',
		dialCodeWithoutPlus: 1664,
		dialCodeWithPlus: '+1664',
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	MQ: {
		isoAlpha3: 'MTQ',
		countryName: 'Martinique',
		unicodeFlag: '🇲🇶',
		dialCodeWithoutPlus: 596,
		dialCodeWithPlus: '+596',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'NA',
		continentName: 'North America'
	},
	MU: {
		isoAlpha3: 'MUS',
		countryName: 'Mauritius',
		unicodeFlag: '🇲🇺',
		dialCodeWithoutPlus: 230,
		dialCodeWithPlus: '+230',
		currencyCode: 'MUR',
		currencyName: 'Mauritian Rupee',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	MW: {
		isoAlpha3: 'MWI',
		countryName: 'Malawi',
		unicodeFlag: '🇲🇼',
		dialCodeWithoutPlus: 265,
		dialCodeWithPlus: '+265',
		currencyCode: 'MWK',
		currencyName: 'Malawian Kwacha',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	MY: {
		isoAlpha3: 'MYS',
		countryName: 'Malaysia',
		unicodeFlag: '🇲🇾',
		dialCodeWithoutPlus: 60,
		dialCodeWithPlus: '+60',
		currencyCode: 'MYR',
		currencyName: 'Ringgit',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	YT: {
		isoAlpha3: 'MYT',
		countryName: 'Mayotte',
		unicodeFlag: '🇾🇹',
		dialCodeWithoutPlus: 262,
		dialCodeWithPlus: '+262',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	NA: {
		isoAlpha3: 'NAM',
		countryName: 'Namibia',
		unicodeFlag: '🇳🇦',
		dialCodeWithoutPlus: 264,
		dialCodeWithPlus: '+264',
		currencyCode: 'NAD',
		currencyName: 'Dollar',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	NC: {
		isoAlpha3: 'NCL',
		countryName: 'New Caledonia',
		unicodeFlag: '🇳🇨',
		dialCodeWithoutPlus: 687,
		dialCodeWithPlus: '+687',
		currencyCode: 'XPF',
		currencyName: 'CFP Franc',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	NE: {
		isoAlpha3: 'NER',
		countryName: 'Niger',
		unicodeFlag: '🇳🇪',
		dialCodeWithoutPlus: 227,
		dialCodeWithPlus: '+227',
		currencyCode: 'XOF',
		currencyName: 'CFA Franc BCEAO',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	NF: {
		isoAlpha3: 'NFK',
		countryName: 'Norfolk Island',
		unicodeFlag: '🇳🇫',
		dialCodeWithoutPlus: 672,
		dialCodeWithPlus: '+672',
		currencyCode: 'AUD',
		currencyName: 'Australian Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	NG: {
		isoAlpha3: 'NGA',
		countryName: 'Nigeria',
		unicodeFlag: '🇳🇬',
		dialCodeWithoutPlus: 234,
		dialCodeWithPlus: '+234',
		currencyCode: 'NGN',
		currencyName: 'Naira',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	NI: {
		isoAlpha3: 'NIC',
		countryName: 'Nicaragua',
		unicodeFlag: '🇳🇮',
		dialCodeWithoutPlus: 505,
		dialCodeWithPlus: '+505',
		currencyCode: 'NIO',
		currencyName: 'Cordoba Oro',
		continentCode: 'NA',
		continentName: 'North America'
	},
	NU: {
		isoAlpha3: 'NIU',
		countryName: 'Niue',
		unicodeFlag: '🇳🇺',
		dialCodeWithoutPlus: 683,
		dialCodeWithPlus: '+683',
		currencyCode: 'NZD',
		currencyName: 'New Zealand Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	NL: {
		isoAlpha3: 'NLD',
		countryName: 'Netherlands',
		unicodeFlag: '🇳🇱',
		dialCodeWithoutPlus: 31,
		dialCodeWithPlus: '+31',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	NO: {
		isoAlpha3: 'NOR',
		countryName: 'Norway',
		unicodeFlag: '🇳🇴',
		dialCodeWithoutPlus: 47,
		dialCodeWithPlus: '+47',
		currencyCode: 'NOK',
		currencyName: 'Norwegian Krone',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	NP: {
		isoAlpha3: 'NPL',
		countryName: 'Nepal',
		unicodeFlag: '🇳🇵',
		dialCodeWithoutPlus: 977,
		dialCodeWithPlus: '+977',
		currencyCode: 'NPR',
		currencyName: 'Nepalese Rupee',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	NR: {
		isoAlpha3: 'NRU',
		countryName: 'Nauru',
		unicodeFlag: '🇳🇷',
		dialCodeWithoutPlus: 674,
		dialCodeWithPlus: '+674',
		currencyCode: 'AUD',
		currencyName: 'Australian Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	NZ: {
		isoAlpha3: 'NZL',
		countryName: 'New Zealand',
		unicodeFlag: '🇳🇿',
		dialCodeWithoutPlus: 64,
		dialCodeWithPlus: '+64',
		currencyCode: 'NZD',
		currencyName: 'New Zealand Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	OM: {
		isoAlpha3: 'OMN',
		countryName: 'Oman',
		unicodeFlag: '🇴🇲',
		dialCodeWithoutPlus: 968,
		dialCodeWithPlus: '+968',
		currencyCode: 'OMR',
		currencyName: 'Sul Rial',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	PK: {
		isoAlpha3: 'PAK',
		countryName: 'Pakistan',
		unicodeFlag: '🇵🇰',
		dialCodeWithoutPlus: 92,
		dialCodeWithPlus: '+92',
		currencyCode: 'PKR',
		currencyName: 'Rupee',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	PA: {
		isoAlpha3: 'PAN',
		countryName: 'Panama',
		unicodeFlag: '🇵🇦',
		dialCodeWithoutPlus: 507,
		dialCodeWithPlus: '+507',
		currencyCode: 'PAB',
		currencyName: 'Balboa',
		continentCode: 'NA',
		continentName: 'North America'
	},
	PN: {
		isoAlpha3: 'PCN',
		countryName: 'Pitcairn',
		unicodeFlag: '🇵🇳',
		dialCodeWithoutPlus: 870,
		dialCodeWithPlus: '+870',
		currencyCode: 'NZD',
		currencyName: 'New Zealand Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	PE: {
		isoAlpha3: 'PER',
		countryName: 'Peru',
		unicodeFlag: '🇵🇪',
		dialCodeWithoutPlus: 51,
		dialCodeWithPlus: '+51',
		currencyCode: 'PEN',
		currencyName: 'Nuevo Sol',
		continentCode: 'SA',
		continentName: 'South America'
	},
	PH: {
		isoAlpha3: 'PHL',
		countryName: 'Philippines',
		unicodeFlag: '🇵🇭',
		dialCodeWithoutPlus: 63,
		dialCodeWithPlus: '+63',
		currencyCode: 'PHP',
		currencyName: 'Peso',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	PW: {
		isoAlpha3: 'PLW',
		countryName: 'Palau',
		unicodeFlag: '🇵🇼',
		dialCodeWithoutPlus: 680,
		dialCodeWithPlus: '+680',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	PG: {
		isoAlpha3: 'PNG',
		countryName: 'Papua New Guinea',
		unicodeFlag: '🇵🇬',
		dialCodeWithoutPlus: 675,
		dialCodeWithPlus: '+675',
		currencyCode: 'PGK',
		currencyName: 'Kina',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	PL: {
		isoAlpha3: 'POL',
		countryName: 'Poland',
		unicodeFlag: '🇵🇱',
		dialCodeWithoutPlus: 48,
		dialCodeWithPlus: '+48',
		currencyCode: 'PLN',
		currencyName: 'Zloty',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	PR: {
		isoAlpha3: 'PRI',
		countryName: 'Puerto Rico',
		unicodeFlag: '🇵🇷',
		dialCodeWithoutPlus: 1,
		dialCodeWithPlus: '+1',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'NA',
		continentName: 'North America'
	},
	KP: {
		isoAlpha3: 'PRK',
		countryName: 'North Korea',
		unicodeFlag: '🇰🇵',
		dialCodeWithoutPlus: 850,
		dialCodeWithPlus: '+850',
		currencyCode: 'KPW',
		currencyName: 'Won',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	PT: {
		isoAlpha3: 'PRT',
		countryName: 'Portugal',
		unicodeFlag: '🇵🇹',
		dialCodeWithoutPlus: 351,
		dialCodeWithPlus: '+351',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	PY: {
		isoAlpha3: 'PRY',
		countryName: 'Paraguay',
		unicodeFlag: '🇵🇾',
		dialCodeWithoutPlus: 595,
		dialCodeWithPlus: '+595',
		currencyCode: 'PYG',
		currencyName: 'Guarani',
		continentCode: 'SA',
		continentName: 'South America'
	},
	PS: {
		isoAlpha3: 'PSE',
		countryName: 'Palestinian Territory',
		unicodeFlag: '🇵🇸',
		dialCodeWithoutPlus: 970,
		dialCodeWithPlus: '+970',
		currencyCode: 'JOD',
		currencyName: 'Jordanian dinar',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	PF: {
		isoAlpha3: 'PYF',
		countryName: 'French Polynesia',
		unicodeFlag: '🇵🇫',
		dialCodeWithoutPlus: 689,
		dialCodeWithPlus: '+689',
		currencyCode: 'XPF',
		currencyName: 'CFP Franc',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	QA: {
		isoAlpha3: 'QAT',
		countryName: 'Qatar',
		unicodeFlag: '🇶🇦',
		dialCodeWithoutPlus: 974,
		dialCodeWithPlus: '+974',
		currencyCode: 'QAR',
		currencyName: 'Rial',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	RE: {
		isoAlpha3: 'REU',
		countryName: 'Réunion',
		unicodeFlag: '🇷🇪',
		dialCodeWithoutPlus: 262,
		dialCodeWithPlus: '+262',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	RO: {
		isoAlpha3: 'ROU',
		countryName: 'Romania',
		unicodeFlag: '🇷🇴',
		dialCodeWithoutPlus: 40,
		dialCodeWithPlus: '+40',
		currencyCode: 'RON',
		currencyName: 'Leu',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	RU: {
		isoAlpha3: 'RUS',
		countryName: 'Russian Federation',
		unicodeFlag: '🇷🇺',
		dialCodeWithoutPlus: 7,
		dialCodeWithPlus: '+7',
		currencyCode: 'RUB',
		currencyName: 'Ruble',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	RW: {
		isoAlpha3: 'RWA',
		countryName: 'Rwanda',
		unicodeFlag: '🇷🇼',
		dialCodeWithoutPlus: 250,
		dialCodeWithPlus: '+250',
		currencyCode: 'RWF',
		currencyName: 'Rwanda Franc',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	SA: {
		isoAlpha3: 'SAU',
		countryName: 'Saudi Arabia',
		unicodeFlag: '🇸🇦',
		dialCodeWithoutPlus: 966,
		dialCodeWithPlus: '+966',
		currencyCode: 'SAR',
		currencyName: 'Riyal',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	SD: {
		isoAlpha3: 'SDN',
		countryName: 'Sudan',
		unicodeFlag: '🇸🇩',
		dialCodeWithoutPlus: 249,
		dialCodeWithPlus: '+249',
		currencyCode: 'SDG',
		currencyName: 'Dinar',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	SN: {
		isoAlpha3: 'SEN',
		countryName: 'Senegal',
		unicodeFlag: '🇸🇳',
		dialCodeWithoutPlus: 221,
		dialCodeWithPlus: '+221',
		currencyCode: 'XOF',
		currencyName: 'CFA Franc BCEAO',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	SG: {
		isoAlpha3: 'SGP',
		countryName: 'Singapore',
		unicodeFlag: '🇸🇬',
		dialCodeWithoutPlus: 65,
		dialCodeWithPlus: '+65',
		currencyCode: 'SGD',
		currencyName: 'Dollar',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	GS: {
		isoAlpha3: 'SGS',
		countryName: 'South Georgia and the South Sandwich Islands',
		unicodeFlag: '🇬🇸',
		dialCodeWithoutPlus: 500,
		dialCodeWithPlus: '+500',
		currencyCode: 'GBP',
		currencyName: 'Sterling',
		continentCode: 'AN',
		continentName: 'Antarctica'
	},
	SH: {
		isoAlpha3: 'SHN',
		countryName: 'Saint Helena, Ascension and Tristan da Cunha',
		unicodeFlag: '🇸🇭',
		dialCodeWithoutPlus: 290,
		dialCodeWithPlus: '+290',
		currencyCode: 'GBP',
		currencyName: 'Saint Helena pound',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	SJ: {
		isoAlpha3: 'SJM',
		countryName: 'Svalbard and Jan Mayen',
		unicodeFlag: '🇸🇯',
		dialCodeWithoutPlus: 47,
		dialCodeWithPlus: '+47',
		currencyCode: 'NOK',
		currencyName: 'Norwegian Krone',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	SB: {
		isoAlpha3: 'SLB',
		countryName: 'Solomon Islands',
		unicodeFlag: '🇸🇧',
		dialCodeWithoutPlus: 677,
		dialCodeWithPlus: '+677',
		currencyCode: 'SBD',
		currencyName: 'Solomon Islands Dollar',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	SL: {
		isoAlpha3: 'SLE',
		countryName: 'Sierra Leone',
		unicodeFlag: '🇸🇱',
		dialCodeWithoutPlus: 232,
		dialCodeWithPlus: '+232',
		currencyCode: 'SLL',
		currencyName: 'Leone',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	SV: {
		isoAlpha3: 'SLV',
		countryName: 'El Salvador',
		unicodeFlag: '🇸🇻',
		dialCodeWithoutPlus: 503,
		dialCodeWithPlus: '+503',
		currencyCode: 'SVC',
		currencyName: 'Salvadoran Colon',
		continentCode: 'NA',
		continentName: 'North America'
	},
	SM: {
		isoAlpha3: 'SMR',
		countryName: 'San Marino',
		unicodeFlag: '🇸🇲',
		dialCodeWithoutPlus: 378,
		dialCodeWithPlus: '+378',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	SO: {
		isoAlpha3: 'SOM',
		countryName: 'Somalia',
		unicodeFlag: '🇸🇴',
		dialCodeWithoutPlus: 252,
		dialCodeWithPlus: '+252',
		currencyCode: 'SOS',
		currencyName: 'Shilling',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	PM: {
		isoAlpha3: 'SPM',
		countryName: 'Saint Pierre and Miquelon',
		unicodeFlag: '🇵🇲',
		dialCodeWithoutPlus: 508,
		dialCodeWithPlus: '+508',
		currencyCode: 'EUR',
		currencyName: 'Euro',
		continentCode: 'NA',
		continentName: 'North America'
	},
	RS: {
		isoAlpha3: 'SRB',
		countryName: 'Serbia',
		unicodeFlag: '🇷🇸',
		dialCodeWithoutPlus: 381,
		dialCodeWithPlus: '+381',
		currencyCode: 'RSD',
		currencyName: 'Serbian dinar',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	SS: {
		isoAlpha3: 'SSD',
		countryName: 'South Sudan',
		unicodeFlag: '🇸🇸',
		dialCodeWithoutPlus: 211,
		dialCodeWithPlus: '+211',
		currencyCode: 'SSP',
		currencyName: 'South Sudanese pound',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	ST: {
		isoAlpha3: 'STP',
		countryName: 'Sao Tome and Principe',
		unicodeFlag: '🇸🇹',
		dialCodeWithoutPlus: 239,
		dialCodeWithPlus: '+239',
		currencyCode: 'STD',
		currencyName: 'Dobra',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	SR: {
		isoAlpha3: 'SUR',
		countryName: 'Suriname',
		unicodeFlag: '🇸🇷',
		dialCodeWithoutPlus: 597,
		dialCodeWithPlus: '+597',
		currencyCode: 'SRD',
		currencyName: 'Surinamese Guilder',
		continentCode: 'SA',
		continentName: 'South America'
	},
	SK: {
		isoAlpha3: 'SVK',
		countryName: 'Slovakia',
		unicodeFlag: '🇸🇰',
		dialCodeWithoutPlus: 421,
		dialCodeWithPlus: '+421',
		currencyCode: 'SKK',
		currencyName: 'Koruna',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	SI: {
		isoAlpha3: 'SVN',
		countryName: 'Slovenia',
		unicodeFlag: '🇸🇮',
		dialCodeWithoutPlus: 386,
		dialCodeWithPlus: '+386',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	SE: {
		isoAlpha3: 'SWE',
		countryName: 'Sweden',
		unicodeFlag: '🇸🇪',
		dialCodeWithoutPlus: 46,
		dialCodeWithPlus: '+46',
		currencyCode: 'SEK',
		currencyName: 'Krona',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	SZ: {
		isoAlpha3: 'SWZ',
		countryName: 'Eswatini',
		unicodeFlag: '🇸🇿',
		dialCodeWithoutPlus: 268,
		dialCodeWithPlus: '+268',
		currencyCode: 'SZL',
		currencyName: 'Lilangeni',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	SX: {
		isoAlpha3: 'SXM',
		countryName: 'Sint Maarten',
		unicodeFlag: '🇸🇽',
		dialCodeWithoutPlus: 1721,
		dialCodeWithPlus: '+1721',
		currencyCode: 'ANG',
		currencyName: 'Netherlands Antillean guilder',
		continentCode: 'NA',
		continentName: 'North America'
	},
	SC: {
		isoAlpha3: 'SYC',
		countryName: 'Seychelles',
		unicodeFlag: '🇸🇨',
		dialCodeWithoutPlus: 248,
		dialCodeWithPlus: '+248',
		currencyCode: 'SCR',
		currencyName: 'Rupee',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	SY: {
		isoAlpha3: 'SYR',
		countryName: 'Syrian Arab Republic',
		unicodeFlag: '🇸🇾',
		dialCodeWithoutPlus: 963,
		dialCodeWithPlus: '+963',
		currencyCode: 'SYP',
		currencyName: 'Syrian Pound',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	TC: {
		isoAlpha3: 'TCA',
		countryName: 'Turks and Caicos Islands',
		unicodeFlag: '🇹🇨',
		dialCodeWithoutPlus: 1649,
		dialCodeWithPlus: '+1649',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'NA',
		continentName: 'North America'
	},
	TD: {
		isoAlpha3: 'TCD',
		countryName: 'Chad',
		unicodeFlag: '🇹🇩',
		dialCodeWithoutPlus: 235,
		dialCodeWithPlus: '+235',
		currencyCode: 'XAF',
		currencyName: 'CFA Franc BEAC',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	TG: {
		isoAlpha3: 'TGO',
		countryName: 'Togo',
		unicodeFlag: '🇹🇬',
		dialCodeWithoutPlus: 228,
		dialCodeWithPlus: '+228',
		currencyCode: 'XOF',
		currencyName: 'CFA Franc BCEAO',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	TH: {
		isoAlpha3: 'THA',
		countryName: 'Thailand',
		unicodeFlag: '🇹🇭',
		dialCodeWithoutPlus: 66,
		dialCodeWithPlus: '+66',
		currencyCode: 'THB',
		currencyName: 'Baht',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	TJ: {
		isoAlpha3: 'TJK',
		countryName: 'Tajikistan',
		unicodeFlag: '🇹🇯',
		dialCodeWithoutPlus: 992,
		dialCodeWithPlus: '+992',
		currencyCode: 'TJS',
		currencyName: 'Tajikistan Ruble',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	TK: {
		isoAlpha3: 'TKL',
		countryName: 'Tokelau',
		unicodeFlag: '🇹🇰',
		dialCodeWithoutPlus: 690,
		dialCodeWithPlus: '+690',
		currencyCode: 'NZD',
		currencyName: 'New Zealand Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	TM: {
		isoAlpha3: 'TKM',
		countryName: 'Turkmenistan',
		unicodeFlag: '🇹🇲',
		dialCodeWithoutPlus: 993,
		dialCodeWithPlus: '+993',
		currencyCode: 'TMT',
		currencyName: 'Manat',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	TL: {
		isoAlpha3: 'TLS',
		countryName: 'East Timor',
		unicodeFlag: '🇹🇱',
		dialCodeWithoutPlus: 670,
		dialCodeWithPlus: '+670',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	TO: {
		isoAlpha3: 'TON',
		countryName: 'Tonga',
		unicodeFlag: '🇹🇴',
		dialCodeWithoutPlus: 676,
		dialCodeWithPlus: '+676',
		currencyCode: 'TOP',
		currencyName: 'PaÕanga',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	TT: {
		isoAlpha3: 'TTO',
		countryName: 'Trinidad and Tobago',
		unicodeFlag: '🇹🇹',
		dialCodeWithoutPlus: 1868,
		dialCodeWithPlus: '+1868',
		currencyCode: 'TTD',
		currencyName: 'Trinidad and Tobago Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	TN: {
		isoAlpha3: 'TUN',
		countryName: 'Tunisia',
		unicodeFlag: '🇹🇳',
		dialCodeWithoutPlus: 216,
		dialCodeWithPlus: '+216',
		currencyCode: 'TND',
		currencyName: 'Tunisian Dinar',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	TR: {
		isoAlpha3: 'TUR',
		countryName: 'Turkey',
		unicodeFlag: '🇹🇷',
		dialCodeWithoutPlus: 90,
		dialCodeWithPlus: '+90',
		currencyCode: 'TRY',
		currencyName: 'Lira',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	TV: {
		isoAlpha3: 'TUV',
		countryName: 'Tuvalu',
		unicodeFlag: '🇹🇻',
		dialCodeWithoutPlus: 688,
		dialCodeWithPlus: '+688',
		currencyCode: 'AUD',
		currencyName: 'Australian Dollars',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	TW: {
		isoAlpha3: 'TWN',
		countryName: 'Taiwan',
		unicodeFlag: '🇹🇼',
		dialCodeWithoutPlus: 886,
		dialCodeWithPlus: '+886',
		currencyCode: 'TWD',
		currencyName: 'Dollar',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	TZ: {
		isoAlpha3: 'TZA',
		countryName: 'Tanzania',
		unicodeFlag: '🇹🇿',
		dialCodeWithoutPlus: 255,
		dialCodeWithPlus: '+255',
		currencyCode: 'TZS',
		currencyName: 'Shilling',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	UG: {
		isoAlpha3: 'UGA',
		countryName: 'Uganda',
		unicodeFlag: '🇺🇬',
		dialCodeWithoutPlus: 256,
		dialCodeWithPlus: '+256',
		currencyCode: 'UGX',
		currencyName: 'Shilling',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	UA: {
		isoAlpha3: 'UKR',
		countryName: 'Ukraine',
		unicodeFlag: '🇺🇦',
		dialCodeWithoutPlus: 380,
		dialCodeWithPlus: '+380',
		currencyCode: 'UAH',
		currencyName: 'Hryvnia',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	UY: {
		isoAlpha3: 'URY',
		countryName: 'Uruguay',
		unicodeFlag: '🇺🇾',
		dialCodeWithoutPlus: 598,
		dialCodeWithPlus: '+598',
		currencyCode: 'UYU',
		currencyName: 'Peso',
		continentCode: 'SA',
		continentName: 'South America'
	},
	US: {
		isoAlpha3: 'USA',
		countryName: 'United States of America',
		unicodeFlag: '🇺🇸',
		dialCodeWithoutPlus: 1,
		dialCodeWithPlus: '+1',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'NA',
		continentName: 'North America'
	},
	UZ: {
		isoAlpha3: 'UZB',
		countryName: 'Uzbekistan',
		unicodeFlag: '🇺🇿',
		dialCodeWithoutPlus: 998,
		dialCodeWithPlus: '+998',
		currencyCode: 'UZS',
		currencyName: 'Som',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	VA: {
		isoAlpha3: 'VAT',
		countryName: 'Holy See',
		unicodeFlag: '🇻🇦',
		dialCodeWithoutPlus: 3906,
		dialCodeWithPlus: '+3906',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'EU',
		continentName: 'Europe'
	},
	VC: {
		isoAlpha3: 'VCT',
		countryName: 'Saint Vincent and the Grenadines',
		unicodeFlag: '🇻🇨',
		dialCodeWithoutPlus: 1784,
		dialCodeWithPlus: '+1784',
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		continentCode: 'NA',
		continentName: 'North America'
	},
	VE: {
		isoAlpha3: 'VEN',
		countryName: 'Venezuela',
		unicodeFlag: '🇻🇪',
		dialCodeWithoutPlus: 58,
		dialCodeWithPlus: '+58',
		currencyCode: 'VEF',
		currencyName: 'Bolivar',
		continentCode: 'SA',
		continentName: 'South America'
	},
	VG: {
		isoAlpha3: 'VGB',
		countryName: 'Virgin Islands (British)',
		unicodeFlag: '🇻🇬',
		dialCodeWithoutPlus: 1284,
		dialCodeWithPlus: '+1284',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'NA',
		continentName: 'North America'
	},
	VI: {
		isoAlpha3: 'VIR',
		countryName: 'Virgin Islands (U.S.)',
		unicodeFlag: '🇻🇮',
		dialCodeWithoutPlus: 1340,
		dialCodeWithPlus: '+1340',
		currencyCode: 'USD',
		currencyName: 'USD',
		continentCode: 'NA',
		continentName: 'North America'
	},
	VN: {
		isoAlpha3: 'VNM',
		countryName: 'Viet Nam',
		unicodeFlag: '🇻🇳',
		dialCodeWithoutPlus: 84,
		dialCodeWithPlus: '+84',
		currencyCode: 'VND',
		currencyName: 'Dong',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	VU: {
		isoAlpha3: 'VUT',
		countryName: 'Vanuatu',
		unicodeFlag: '🇻🇺',
		dialCodeWithoutPlus: 678,
		dialCodeWithPlus: '+678',
		currencyCode: 'VUV',
		currencyName: 'Vatu',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	WF: {
		isoAlpha3: 'WLF',
		countryName: 'Wallis and Futuna',
		unicodeFlag: '🇼🇫',
		dialCodeWithoutPlus: 681,
		dialCodeWithPlus: '+681',
		currencyCode: 'XPF',
		currencyName: 'CFP Franc',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	WS: {
		isoAlpha3: 'WSM',
		countryName: 'Samoa',
		unicodeFlag: '🇼🇸',
		dialCodeWithoutPlus: 685,
		dialCodeWithPlus: '+685',
		currencyCode: 'EUR',
		currencyName: 'Euros',
		continentCode: 'OC',
		continentName: 'Oceania'
	},
	YE: {
		isoAlpha3: 'YEM',
		countryName: 'Yemen',
		unicodeFlag: '🇾🇪',
		dialCodeWithoutPlus: 967,
		dialCodeWithPlus: '+967',
		currencyCode: 'YER',
		currencyName: 'Rial',
		continentCode: 'AS',
		continentName: 'Asia'
	},
	ZA: {
		isoAlpha3: 'ZAF',
		countryName: 'South Africa',
		unicodeFlag: '🇿🇦',
		dialCodeWithoutPlus: 27,
		dialCodeWithPlus: '+27',
		currencyCode: 'ZAR',
		currencyName: 'Rand',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	ZM: {
		isoAlpha3: 'ZMB',
		countryName: 'Zambia',
		unicodeFlag: '🇿🇲',
		dialCodeWithoutPlus: 260,
		dialCodeWithPlus: '+260',
		currencyCode: 'ZMK',
		currencyName: 'Kwacha',
		continentCode: 'AF',
		continentName: 'Africa'
	},
	ZW: {
		isoAlpha3: 'ZWE',
		countryName: 'Zimbabwe',
		unicodeFlag: '🇿🇼',
		dialCodeWithoutPlus: 263,
		dialCodeWithPlus: '+263',
		currencyCode: 'ZWD',
		currencyName: 'Zimbabwe Dollar',
		continentCode: 'AF',
		continentName: 'Africa'
	}
};

module.exports.ISOAlpha2Mapping = Alpha2Mapping;

module.exports.isValidAlpha2Code = val => typeof val === 'string' && Alpha2Mapping[val] !== undefined;
